//! Generated by `genbsdsyscalls.py`, DO NOT EDIT.

use std::io::Result as IoResult;

use crate::{
    aarch64::{cpu::Cpu, syscall::bsd::*},
    utils::ptr::Uintptr,
};

#[inline]
pub fn read(_cpu: &Cpu, _args: ARG_read) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn write(_cpu: &Cpu, _args: ARG_write) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn open(_cpu: &Cpu, _args: ARG_open) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn wait4(_cpu: &Cpu, _args: ARG_wait4) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn link(_cpu: &Cpu, _args: ARG_link) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn unlink(_cpu: &Cpu, _args: ARG_unlink) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_chdir(_cpu: &Cpu, _args: ARG_sys_chdir) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mknod(_cpu: &Cpu, _args: ARG_mknod) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn chmod(_cpu: &Cpu, _args: ARG_chmod) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn chown(_cpu: &Cpu, _args: ARG_chown) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getfsstat(_cpu: &Cpu, _args: ARG_getfsstat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ptrace(_cpu: &Cpu, _args: ARG_ptrace) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn recvmsg(_cpu: &Cpu, _args: ARG_recvmsg) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sendmsg(_cpu: &Cpu, _args: ARG_sendmsg) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn recvfrom(_cpu: &Cpu, _args: ARG_recvfrom) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn accept(_cpu: &Cpu, _args: ARG_accept) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getpeername(_cpu: &Cpu, _args: ARG_getpeername) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getsockname(_cpu: &Cpu, _args: ARG_getsockname) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn access(_cpu: &Cpu, _args: ARG_access) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn chflags(_cpu: &Cpu, _args: ARG_chflags) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sigaction(_cpu: &Cpu, _args: ARG_sigaction) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sigprocmask(_cpu: &Cpu, _args: ARG_sigprocmask) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getlogin(_cpu: &Cpu, _args: ARG_getlogin) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setlogin(_cpu: &Cpu, _args: ARG_setlogin) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn acct(_cpu: &Cpu, _args: ARG_acct) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sigpending(_cpu: &Cpu, _args: ARG_sigpending) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sigaltstack(_cpu: &Cpu, _args: ARG_sigaltstack) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ioctl(_cpu: &Cpu, _args: ARG_ioctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn reboot(_cpu: &Cpu, _args: ARG_reboot) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn revoke(_cpu: &Cpu, _args: ARG_revoke) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn symlink(_cpu: &Cpu, _args: ARG_symlink) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn readlink(_cpu: &Cpu, _args: ARG_readlink) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn execve(_cpu: &Cpu, _args: ARG_execve) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn chroot(_cpu: &Cpu, _args: ARG_chroot) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msync(_cpu: &Cpu, _args: ARG_msync) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn oslog_coproc_reg(_cpu: &Cpu, _args: ARG_oslog_coproc_reg) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn oslog_coproc(_cpu: &Cpu, _args: ARG_oslog_coproc) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn munmap(_cpu: &Cpu, _args: ARG_munmap) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mprotect(_cpu: &Cpu, _args: ARG_mprotect) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn madvise(_cpu: &Cpu, _args: ARG_madvise) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mincore(_cpu: &Cpu, _args: ARG_mincore) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getgroups(_cpu: &Cpu, _args: ARG_getgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setgroups(_cpu: &Cpu, _args: ARG_setgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setitimer(_cpu: &Cpu, _args: ARG_setitimer) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getitimer(_cpu: &Cpu, _args: ARG_getitimer) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn select(_cpu: &Cpu, _args: ARG_select) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn connect(_cpu: &Cpu, _args: ARG_connect) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn bind(_cpu: &Cpu, _args: ARG_bind) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setsockopt(_cpu: &Cpu, _args: ARG_setsockopt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn gettimeofday(_cpu: &Cpu, _args: ARG_gettimeofday) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getrusage(_cpu: &Cpu, _args: ARG_getrusage) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getsockopt(_cpu: &Cpu, _args: ARG_getsockopt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn readv(_cpu: &Cpu, _args: ARG_readv) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn writev(_cpu: &Cpu, _args: ARG_writev) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn settimeofday(_cpu: &Cpu, _args: ARG_settimeofday) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn rename(_cpu: &Cpu, _args: ARG_rename) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mkfifo(_cpu: &Cpu, _args: ARG_mkfifo) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sendto(_cpu: &Cpu, _args: ARG_sendto) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn socketpair(_cpu: &Cpu, _args: ARG_socketpair) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mkdir(_cpu: &Cpu, _args: ARG_mkdir) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn rmdir(_cpu: &Cpu, _args: ARG_rmdir) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn utimes(_cpu: &Cpu, _args: ARG_utimes) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn futimes(_cpu: &Cpu, _args: ARG_futimes) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn adjtime(_cpu: &Cpu, _args: ARG_adjtime) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn gethostuuid(_cpu: &Cpu, _args: ARG_gethostuuid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn pread(_cpu: &Cpu, _args: ARG_pread) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn pwrite(_cpu: &Cpu, _args: ARG_pwrite) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn nfssvc(_cpu: &Cpu, _args: ARG_nfssvc) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn statfs(_cpu: &Cpu, _args: ARG_statfs) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fstatfs(_cpu: &Cpu, _args: ARG_fstatfs) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn unmount(_cpu: &Cpu, _args: ARG_unmount) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getfh(_cpu: &Cpu, _args: ARG_getfh) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn quotactl(_cpu: &Cpu, _args: ARG_quotactl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mount(_cpu: &Cpu, _args: ARG_mount) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn csops(_cpu: &Cpu, _args: ARG_csops) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn csops_audittoken(_cpu: &Cpu, _args: ARG_csops_audittoken) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn waitid(_cpu: &Cpu, _args: ARG_waitid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kdebug_typefilter(_cpu: &Cpu, _args: ARG_kdebug_typefilter) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kdebug_trace_string(_cpu: &Cpu, _args: ARG_kdebug_trace_string) -> IoResult<u64> {
    todo!();
}

#[inline]
pub fn sigreturn(_cpu: &Cpu, _args: ARG_sigreturn) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_panic_with_data(_cpu: &Cpu, _args: ARG_sys_panic_with_data) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn thread_selfcounts(_cpu: &Cpu, _args: ARG_thread_selfcounts) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn stat(_cpu: &Cpu, _args: ARG_stat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_fstat(_cpu: &Cpu, _args: ARG_sys_fstat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn lstat(_cpu: &Cpu, _args: ARG_lstat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn pathconf(_cpu: &Cpu, _args: ARG_pathconf) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getrlimit(_cpu: &Cpu, _args: ARG_getrlimit) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setrlimit(_cpu: &Cpu, _args: ARG_setrlimit) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getdirentries(_cpu: &Cpu, _args: ARG_getdirentries) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mmap(_cpu: &Cpu, _args: ARG_mmap) -> IoResult<Uintptr> {
    todo!();
}

#[inline]
pub fn truncate(_cpu: &Cpu, _args: ARG_truncate) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sysctl(_cpu: &Cpu, _args: ARG_sysctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mlock(_cpu: &Cpu, _args: ARG_mlock) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn munlock(_cpu: &Cpu, _args: ARG_munlock) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn undelete(_cpu: &Cpu, _args: ARG_undelete) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn open_dprotected_np(_cpu: &Cpu, _args: ARG_open_dprotected_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fsgetpath_ext(_cpu: &Cpu, _args: ARG_fsgetpath_ext) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn openat_dprotected_np(_cpu: &Cpu, _args: ARG_openat_dprotected_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getattrlist(_cpu: &Cpu, _args: ARG_getattrlist) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setattrlist(_cpu: &Cpu, _args: ARG_setattrlist) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getdirentriesattr(_cpu: &Cpu, _args: ARG_getdirentriesattr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn exchangedata(_cpu: &Cpu, _args: ARG_exchangedata) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn searchfs(_cpu: &Cpu, _args: ARG_searchfs) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn delete(_cpu: &Cpu, _args: ARG_delete) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn copyfile(_cpu: &Cpu, _args: ARG_copyfile) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fgetattrlist(_cpu: &Cpu, _args: ARG_fgetattrlist) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fsetattrlist(_cpu: &Cpu, _args: ARG_fsetattrlist) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn poll(_cpu: &Cpu, _args: ARG_poll) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getxattr(_cpu: &Cpu, _args: ARG_getxattr) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn fgetxattr(_cpu: &Cpu, _args: ARG_fgetxattr) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn setxattr(_cpu: &Cpu, _args: ARG_setxattr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fsetxattr(_cpu: &Cpu, _args: ARG_fsetxattr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn removexattr(_cpu: &Cpu, _args: ARG_removexattr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fremovexattr(_cpu: &Cpu, _args: ARG_fremovexattr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn listxattr(_cpu: &Cpu, _args: ARG_listxattr) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn flistxattr(_cpu: &Cpu, _args: ARG_flistxattr) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn fsctl(_cpu: &Cpu, _args: ARG_fsctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn initgroups(_cpu: &Cpu, _args: ARG_initgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn posix_spawn(_cpu: &Cpu, _args: ARG_posix_spawn) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ffsctl(_cpu: &Cpu, _args: ARG_ffsctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fhopen(_cpu: &Cpu, _args: ARG_fhopen) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn minherit(_cpu: &Cpu, _args: ARG_minherit) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn semop(_cpu: &Cpu, _args: ARG_semop) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msgctl(_cpu: &Cpu, _args: ARG_msgctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msgsnd(_cpu: &Cpu, _args: ARG_msgsnd) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msgrcv(_cpu: &Cpu, _args: ARG_msgrcv) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn shmat(_cpu: &Cpu, _args: ARG_shmat) -> IoResult<Uintptr> {
    todo!();
}

#[inline]
pub fn shmctl(_cpu: &Cpu, _args: ARG_shmctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn shmdt(_cpu: &Cpu, _args: ARG_shmdt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn shm_open(_cpu: &Cpu, _args: ARG_shm_open) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn shm_unlink(_cpu: &Cpu, _args: ARG_shm_unlink) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sem_open(_cpu: &Cpu, _args: ARG_sem_open) -> IoResult<Uintptr> {
    todo!();
}

#[inline]
pub fn sem_close(_cpu: &Cpu, _args: ARG_sem_close) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sem_unlink(_cpu: &Cpu, _args: ARG_sem_unlink) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sem_wait(_cpu: &Cpu, _args: ARG_sem_wait) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sem_trywait(_cpu: &Cpu, _args: ARG_sem_trywait) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sem_post(_cpu: &Cpu, _args: ARG_sem_post) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_sysctlbyname(_cpu: &Cpu, _args: ARG_sys_sysctlbyname) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn open_extended(_cpu: &Cpu, _args: ARG_open_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn umask_extended(_cpu: &Cpu, _args: ARG_umask_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn stat_extended(_cpu: &Cpu, _args: ARG_stat_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn lstat_extended(_cpu: &Cpu, _args: ARG_lstat_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_fstat_extended(_cpu: &Cpu, _args: ARG_sys_fstat_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn chmod_extended(_cpu: &Cpu, _args: ARG_chmod_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fchmod_extended(_cpu: &Cpu, _args: ARG_fchmod_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn access_extended(_cpu: &Cpu, _args: ARG_access_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn gettid(_cpu: &Cpu, _args: ARG_gettid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setsgroups(_cpu: &Cpu, _args: ARG_setsgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getsgroups(_cpu: &Cpu, _args: ARG_getsgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setwgroups(_cpu: &Cpu, _args: ARG_setwgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getwgroups(_cpu: &Cpu, _args: ARG_getwgroups) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mkfifo_extended(_cpu: &Cpu, _args: ARG_mkfifo_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mkdir_extended(_cpu: &Cpu, _args: ARG_mkdir_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn identitysvc(_cpu: &Cpu, _args: ARG_identitysvc) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn shared_region_check_np(_cpu: &Cpu, _args: ARG_shared_region_check_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn vm_pressure_monitor(_cpu: &Cpu, _args: ARG_vm_pressure_monitor) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn psynch_rw_longrdlock(_cpu: &Cpu, _args: ARG_psynch_rw_longrdlock) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_rw_yieldwrlock(_cpu: &Cpu, _args: ARG_psynch_rw_yieldwrlock) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_rw_downgrade(_cpu: &Cpu, _args: ARG_psynch_rw_downgrade) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn psynch_rw_upgrade(_cpu: &Cpu, _args: ARG_psynch_rw_upgrade) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_mutexwait(_cpu: &Cpu, _args: ARG_psynch_mutexwait) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_mutexdrop(_cpu: &Cpu, _args: ARG_psynch_mutexdrop) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_cvbroad(_cpu: &Cpu, _args: ARG_psynch_cvbroad) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_cvsignal(_cpu: &Cpu, _args: ARG_psynch_cvsignal) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_cvwait(_cpu: &Cpu, _args: ARG_psynch_cvwait) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_rw_rdlock(_cpu: &Cpu, _args: ARG_psynch_rw_rdlock) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_rw_wrlock(_cpu: &Cpu, _args: ARG_psynch_rw_wrlock) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_rw_unlock(_cpu: &Cpu, _args: ARG_psynch_rw_unlock) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_rw_unlock2(_cpu: &Cpu, _args: ARG_psynch_rw_unlock2) -> IoResult<u32> {
    todo!();
}

#[inline]
pub fn psynch_cvclrprepost(_cpu: &Cpu, _args: ARG_psynch_cvclrprepost) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_fsync(_cpu: &Cpu, _args: ARG_aio_fsync) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_return(_cpu: &Cpu, _args: ARG_aio_return) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn aio_suspend(_cpu: &Cpu, _args: ARG_aio_suspend) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_cancel(_cpu: &Cpu, _args: ARG_aio_cancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_error(_cpu: &Cpu, _args: ARG_aio_error) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_read(_cpu: &Cpu, _args: ARG_aio_read) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_write(_cpu: &Cpu, _args: ARG_aio_write) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn lio_listio(_cpu: &Cpu, _args: ARG_lio_listio) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn iopolicysys(_cpu: &Cpu, _args: ARG_iopolicysys) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn process_policy(_cpu: &Cpu, _args: ARG_process_policy) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __pthread_sigmask(_cpu: &Cpu, _args: ARG___pthread_sigmask) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __sigwait(_cpu: &Cpu, _args: ARG___sigwait) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn proc_info(_cpu: &Cpu, _args: ARG_proc_info) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sendfile(_cpu: &Cpu, _args: ARG_sendfile) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn stat64(_cpu: &Cpu, _args: ARG_stat64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_fstat64(_cpu: &Cpu, _args: ARG_sys_fstat64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn lstat64(_cpu: &Cpu, _args: ARG_lstat64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn stat64_extended(_cpu: &Cpu, _args: ARG_stat64_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn lstat64_extended(_cpu: &Cpu, _args: ARG_lstat64_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_fstat64_extended(_cpu: &Cpu, _args: ARG_sys_fstat64_extended) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getdirentries64(_cpu: &Cpu, _args: ARG_getdirentries64) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn statfs64(_cpu: &Cpu, _args: ARG_statfs64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fstatfs64(_cpu: &Cpu, _args: ARG_fstatfs64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getfsstat64(_cpu: &Cpu, _args: ARG_getfsstat64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __pthread_chdir(_cpu: &Cpu, _args: ARG___pthread_chdir) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn audit(_cpu: &Cpu, _args: ARG_audit) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn auditon(_cpu: &Cpu, _args: ARG_auditon) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getauid(_cpu: &Cpu, _args: ARG_getauid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setauid(_cpu: &Cpu, _args: ARG_setauid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getaudit_addr(_cpu: &Cpu, _args: ARG_getaudit_addr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setaudit_addr(_cpu: &Cpu, _args: ARG_setaudit_addr) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn auditctl(_cpu: &Cpu, _args: ARG_auditctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn bsdthread_create(_cpu: &Cpu, _args: ARG_bsdthread_create) -> IoResult<Uintptr> {
    todo!();
}

#[inline]
pub fn bsdthread_terminate(_cpu: &Cpu, _args: ARG_bsdthread_terminate) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kevent(_cpu: &Cpu, _args: ARG_kevent) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn lchown(_cpu: &Cpu, _args: ARG_lchown) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn bsdthread_register(_cpu: &Cpu, _args: ARG_bsdthread_register) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn workq_kernreturn(_cpu: &Cpu, _args: ARG_workq_kernreturn) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kevent64(_cpu: &Cpu, _args: ARG_kevent64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ledger(_cpu: &Cpu, _args: ARG_ledger) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kevent_qos(_cpu: &Cpu, _args: ARG_kevent_qos) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kevent_id(_cpu: &Cpu, _args: ARG_kevent_id) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_execve(_cpu: &Cpu, _args: ARG___mac_execve) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_syscall(_cpu: &Cpu, _args: ARG___mac_syscall) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_get_file(_cpu: &Cpu, _args: ARG___mac_get_file) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_set_file(_cpu: &Cpu, _args: ARG___mac_set_file) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_get_link(_cpu: &Cpu, _args: ARG___mac_get_link) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_set_link(_cpu: &Cpu, _args: ARG___mac_set_link) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_get_proc(_cpu: &Cpu, _args: ARG___mac_get_proc) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_set_proc(_cpu: &Cpu, _args: ARG___mac_set_proc) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_get_fd(_cpu: &Cpu, _args: ARG___mac_get_fd) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_set_fd(_cpu: &Cpu, _args: ARG___mac_set_fd) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_get_pid(_cpu: &Cpu, _args: ARG___mac_get_pid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn pselect(_cpu: &Cpu, _args: ARG_pselect) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn pselect_nocancel(_cpu: &Cpu, _args: ARG_pselect_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn read_nocancel(_cpu: &Cpu, _args: ARG_read_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn write_nocancel(_cpu: &Cpu, _args: ARG_write_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn open_nocancel(_cpu: &Cpu, _args: ARG_open_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn wait4_nocancel(_cpu: &Cpu, _args: ARG_wait4_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn recvmsg_nocancel(_cpu: &Cpu, _args: ARG_recvmsg_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sendmsg_nocancel(_cpu: &Cpu, _args: ARG_sendmsg_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn recvfrom_nocancel(_cpu: &Cpu, _args: ARG_recvfrom_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn accept_nocancel(_cpu: &Cpu, _args: ARG_accept_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msync_nocancel(_cpu: &Cpu, _args: ARG_msync_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn select_nocancel(_cpu: &Cpu, _args: ARG_select_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn connect_nocancel(_cpu: &Cpu, _args: ARG_connect_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn readv_nocancel(_cpu: &Cpu, _args: ARG_readv_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn writev_nocancel(_cpu: &Cpu, _args: ARG_writev_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sendto_nocancel(_cpu: &Cpu, _args: ARG_sendto_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn pread_nocancel(_cpu: &Cpu, _args: ARG_pread_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn pwrite_nocancel(_cpu: &Cpu, _args: ARG_pwrite_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn waitid_nocancel(_cpu: &Cpu, _args: ARG_waitid_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn poll_nocancel(_cpu: &Cpu, _args: ARG_poll_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msgsnd_nocancel(_cpu: &Cpu, _args: ARG_msgsnd_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn msgrcv_nocancel(_cpu: &Cpu, _args: ARG_msgrcv_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sem_wait_nocancel(_cpu: &Cpu, _args: ARG_sem_wait_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn aio_suspend_nocancel(_cpu: &Cpu, _args: ARG_aio_suspend_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __sigwait_nocancel(_cpu: &Cpu, _args: ARG___sigwait_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_mount(_cpu: &Cpu, _args: ARG___mac_mount) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_get_mount(_cpu: &Cpu, _args: ARG___mac_get_mount) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __mac_getfsstat(_cpu: &Cpu, _args: ARG___mac_getfsstat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fsgetpath(_cpu: &Cpu, _args: ARG_fsgetpath) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sys_fileport_makeport(_cpu: &Cpu, _args: ARG_sys_fileport_makeport) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn audit_session_port(_cpu: &Cpu, _args: ARG_audit_session_port) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kas_info(_cpu: &Cpu, _args: ARG_kas_info) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn memorystatus_control(_cpu: &Cpu, _args: ARG_memorystatus_control) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn guarded_open_np(_cpu: &Cpu, _args: ARG_guarded_open_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn guarded_close_np(_cpu: &Cpu, _args: ARG_guarded_close_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn guarded_kqueue_np(_cpu: &Cpu, _args: ARG_guarded_kqueue_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn change_fdguard_np(_cpu: &Cpu, _args: ARG_change_fdguard_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn proc_rlimit_control(_cpu: &Cpu, _args: ARG_proc_rlimit_control) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn connectx(_cpu: &Cpu, _args: ARG_connectx) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn memorystatus_get_level(_cpu: &Cpu, _args: ARG_memorystatus_get_level) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sfi_ctl(_cpu: &Cpu, _args: ARG_sfi_ctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sfi_pidctl(_cpu: &Cpu, _args: ARG_sfi_pidctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn coalition(_cpu: &Cpu, _args: ARG_coalition) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn coalition_info(_cpu: &Cpu, _args: ARG_coalition_info) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn necp_match_policy(_cpu: &Cpu, _args: ARG_necp_match_policy) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getattrlistbulk(_cpu: &Cpu, _args: ARG_getattrlistbulk) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn clonefileat(_cpu: &Cpu, _args: ARG_clonefileat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn openat(_cpu: &Cpu, _args: ARG_openat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn openat_nocancel(_cpu: &Cpu, _args: ARG_openat_nocancel) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn renameat(_cpu: &Cpu, _args: ARG_renameat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn faccessat(_cpu: &Cpu, _args: ARG_faccessat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fchmodat(_cpu: &Cpu, _args: ARG_fchmodat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fchownat(_cpu: &Cpu, _args: ARG_fchownat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fstatat(_cpu: &Cpu, _args: ARG_fstatat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fstatat64(_cpu: &Cpu, _args: ARG_fstatat64) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn linkat(_cpu: &Cpu, _args: ARG_linkat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn unlinkat(_cpu: &Cpu, _args: ARG_unlinkat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn readlinkat(_cpu: &Cpu, _args: ARG_readlinkat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn symlinkat(_cpu: &Cpu, _args: ARG_symlinkat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mkdirat(_cpu: &Cpu, _args: ARG_mkdirat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getattrlistat(_cpu: &Cpu, _args: ARG_getattrlistat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn bsdthread_ctl(_cpu: &Cpu, _args: ARG_bsdthread_ctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn openbyid_np(_cpu: &Cpu, _args: ARG_openbyid_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn recvmsg_x(_cpu: &Cpu, _args: ARG_recvmsg_x) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sendmsg_x(_cpu: &Cpu, _args: ARG_sendmsg_x) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn csrctl(_cpu: &Cpu, _args: ARG_csrctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn guarded_open_dprotected_np(
    _cpu: &Cpu,
    _args: ARG_guarded_open_dprotected_np,
) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn guarded_write_np(_cpu: &Cpu, _args: ARG_guarded_write_np) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn guarded_pwrite_np(_cpu: &Cpu, _args: ARG_guarded_pwrite_np) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn guarded_writev_np(_cpu: &Cpu, _args: ARG_guarded_writev_np) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn renameatx_np(_cpu: &Cpu, _args: ARG_renameatx_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mremap_encrypted(_cpu: &Cpu, _args: ARG_mremap_encrypted) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn stack_snapshot_with_config(
    _cpu: &Cpu,
    _args: ARG_stack_snapshot_with_config,
) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn microstackshot(_cpu: &Cpu, _args: ARG_microstackshot) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn grab_pgo_data(_cpu: &Cpu, _args: ARG_grab_pgo_data) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn persona(_cpu: &Cpu, _args: ARG_persona) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn work_interval_ctl(_cpu: &Cpu, _args: ARG_work_interval_ctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn getentropy(_cpu: &Cpu, _args: ARG_getentropy) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn necp_client_action(_cpu: &Cpu, _args: ARG_necp_client_action) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __nexus_open(_cpu: &Cpu, _args: ARG___nexus_open) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __nexus_register(_cpu: &Cpu, _args: ARG___nexus_register) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __nexus_create(_cpu: &Cpu, _args: ARG___nexus_create) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __nexus_get_opt(_cpu: &Cpu, _args: ARG___nexus_get_opt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __nexus_set_opt(_cpu: &Cpu, _args: ARG___nexus_set_opt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __channel_open(_cpu: &Cpu, _args: ARG___channel_open) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __channel_get_info(_cpu: &Cpu, _args: ARG___channel_get_info) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __channel_get_opt(_cpu: &Cpu, _args: ARG___channel_get_opt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn __channel_set_opt(_cpu: &Cpu, _args: ARG___channel_set_opt) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_ulock_wait(_cpu: &Cpu, _args: ARG_sys_ulock_wait) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_ulock_wake(_cpu: &Cpu, _args: ARG_sys_ulock_wake) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fclonefileat(_cpu: &Cpu, _args: ARG_fclonefileat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fs_snapshot(_cpu: &Cpu, _args: ARG_fs_snapshot) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn terminate_with_payload(_cpu: &Cpu, _args: ARG_terminate_with_payload) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn abort_with_payload(_cpu: &Cpu, _args: ARG_abort_with_payload) -> IoResult<()> {
    todo!();
}

#[inline]
pub fn necp_session_action(_cpu: &Cpu, _args: ARG_necp_session_action) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn setattrlistat(_cpu: &Cpu, _args: ARG_setattrlistat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn net_qos_guideline(_cpu: &Cpu, _args: ARG_net_qos_guideline) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn fmount(_cpu: &Cpu, _args: ARG_fmount) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ntp_adjtime(_cpu: &Cpu, _args: ARG_ntp_adjtime) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ntp_gettime(_cpu: &Cpu, _args: ARG_ntp_gettime) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn os_fault_with_payload(_cpu: &Cpu, _args: ARG_os_fault_with_payload) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn kqueue_workloop_ctl(_cpu: &Cpu, _args: ARG_kqueue_workloop_ctl) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn coalition_ledger(_cpu: &Cpu, _args: ARG_coalition_ledger) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn log_data(_cpu: &Cpu, _args: ARG_log_data) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn shared_region_map_and_slide_2_np(
    _cpu: &Cpu,
    _args: ARG_shared_region_map_and_slide_2_np,
) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn pivot_root(_cpu: &Cpu, _args: ARG_pivot_root) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn task_inspect_for_pid(_cpu: &Cpu, _args: ARG_task_inspect_for_pid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn task_read_for_pid(_cpu: &Cpu, _args: ARG_task_read_for_pid) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_preadv(_cpu: &Cpu, _args: ARG_sys_preadv) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sys_pwritev(_cpu: &Cpu, _args: ARG_sys_pwritev) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sys_preadv_nocancel(_cpu: &Cpu, _args: ARG_sys_preadv_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sys_pwritev_nocancel(_cpu: &Cpu, _args: ARG_sys_pwritev_nocancel) -> IoResult<isize> {
    todo!();
}

#[inline]
pub fn sys_ulock_wait2(_cpu: &Cpu, _args: ARG_sys_ulock_wait2) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn proc_info_extended_id(_cpu: &Cpu, _args: ARG_proc_info_extended_id) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn tracker_action(_cpu: &Cpu, _args: ARG_tracker_action) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn graftdmg(_cpu: &Cpu, _args: ARG_graftdmg) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn map_with_linking_np(_cpu: &Cpu, _args: ARG_map_with_linking_np) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn freadlink(_cpu: &Cpu, _args: ARG_freadlink) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn sys_record_system_event(_cpu: &Cpu, _args: ARG_sys_record_system_event) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mkfifoat(_cpu: &Cpu, _args: ARG_mkfifoat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn mknodat(_cpu: &Cpu, _args: ARG_mknodat) -> IoResult<i32> {
    todo!();
}

#[inline]
pub fn ungraftdmg(_cpu: &Cpu, _args: ARG_ungraftdmg) -> IoResult<i32> {
    todo!();
}
