//! Generated by `genbsdsyscalls.py`, DO NOT EDIT.

use crate::{
    aarch64::{
        cpu::Cpu,
        syscall::{bsd::*, sys},
        virtos::mem::VmMap,
    },
    utils::ptr::VMA,
};

trait ToSize: Copy {
    fn to_size(self) -> usize;
}

macro_rules! impl_bsd_result {
    ($($({$($bounds:tt)*})? $ty:ty),+ $(,)?) => {
        $(
            impl<$($($bounds)*)?> ToSize for $ty {
                #[inline(always)]
                fn to_size(self) -> usize {
                    self as usize
                }
            }
        )+
    };
}

impl_bsd_result! {
    u8,
    u16,
    u32,
    u64,
    usize,
    i8,
    i16,
    i32,
    i64,
    isize,
}

macro_rules! at {
    ($cpu:expr, $addr:expr, $size:expr) => {{
        if let Some(addr) = VmMap::populate($cpu, $addr, $size) {
            addr.as_u64()
        } else {
            return (libc::EFAULT as u64, false);
        }
    }};
}

#[inline]
pub fn read(cpu: &Cpu, args: ARG_read) -> (u64, bool) {
    let ARG_read { fd, cbuf, nbyte } = args;
    sys::syscall(
        3,
        [
            fd as u64,
            at!(cpu, cbuf, ToSize::to_size(nbyte)),
            nbyte as u64,
        ],
    )
}

#[inline]
pub fn write(cpu: &Cpu, args: ARG_write) -> (u64, bool) {
    let ARG_write { fd, cbuf, nbyte } = args;
    sys::syscall(
        4,
        [
            fd as u64,
            at!(cpu, cbuf, ToSize::to_size(nbyte)),
            nbyte as u64,
        ],
    )
}

#[inline]
pub fn open(cpu: &Cpu, args: ARG_open) -> (u64, bool) {
    let ARG_open { path, flags, mode } = args;
    sys::syscall(
        5,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn wait4(cpu: &Cpu, args: ARG_wait4) -> (u64, bool) {
    let ARG_wait4 {
        pid,
        status,
        options,
        rusage,
    } = args;
    sys::syscall(
        7,
        [
            pid as u64,
            at!(cpu, status, ToSize::to_size(4)),
            options as u64,
            at!(cpu, rusage, ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn link(cpu: &Cpu, args: ARG_link) -> (u64, bool) {
    let ARG_link { path, link } = args;
    sys::syscall(
        9,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, link.vma(), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn unlink(cpu: &Cpu, args: ARG_unlink) -> (u64, bool) {
    let ARG_unlink { path } = args;
    sys::syscall(
        10,
        [at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn sys_chdir(cpu: &Cpu, args: ARG_sys_chdir) -> (u64, bool) {
    let ARG_sys_chdir { path } = args;
    sys::syscall(
        12,
        [at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn mknod(cpu: &Cpu, args: ARG_mknod) -> (u64, bool) {
    let ARG_mknod { path, mode, dev } = args;
    sys::syscall(
        14,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
            dev as u64,
        ],
    )
}

#[inline]
pub fn chmod(cpu: &Cpu, args: ARG_chmod) -> (u64, bool) {
    let ARG_chmod { path, mode } = args;
    sys::syscall(
        15,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
        ],
    )
}

#[inline]
pub fn chown(cpu: &Cpu, args: ARG_chown) -> (u64, bool) {
    let ARG_chown { path, uid, gid } = args;
    sys::syscall(
        16,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            uid as u64,
            gid as u64,
        ],
    )
}

#[inline]
pub fn getfsstat(cpu: &Cpu, args: ARG_getfsstat) -> (u64, bool) {
    let ARG_getfsstat {
        buf,
        bufsize,
        flags,
    } = args;
    sys::syscall(
        18,
        [
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
            flags as u64,
        ],
    )
}

#[inline]
pub fn ptrace(cpu: &Cpu, args: ARG_ptrace) -> (u64, bool) {
    todo!("ptrace({args:?}): {cpu:#?}");
}

#[inline]
pub fn recvmsg(cpu: &Cpu, args: ARG_recvmsg) -> (u64, bool) {
    todo!("recvmsg({args:?}): {cpu:#?}");
}

#[inline]
pub fn sendmsg(cpu: &Cpu, args: ARG_sendmsg) -> (u64, bool) {
    todo!("sendmsg({args:?}): {cpu:#?}");
}

#[inline]
pub fn recvfrom(cpu: &Cpu, args: ARG_recvfrom) -> (u64, bool) {
    todo!("recvfrom({args:?}): {cpu:#?}");
}

#[inline]
pub fn accept(cpu: &Cpu, args: ARG_accept) -> (u64, bool) {
    todo!("accept({args:?}): {cpu:#?}");
}

#[inline]
pub fn getpeername(cpu: &Cpu, args: ARG_getpeername) -> (u64, bool) {
    todo!("getpeername({args:?}): {cpu:#?}");
}

#[inline]
pub fn getsockname(cpu: &Cpu, args: ARG_getsockname) -> (u64, bool) {
    todo!("getsockname({args:?}): {cpu:#?}");
}

#[inline]
pub fn access(cpu: &Cpu, args: ARG_access) -> (u64, bool) {
    let ARG_access { path, flags } = args;
    sys::syscall(
        33,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
        ],
    )
}

#[inline]
pub fn chflags(cpu: &Cpu, args: ARG_chflags) -> (u64, bool) {
    let ARG_chflags { path, flags } = args;
    sys::syscall(
        34,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            flags as u64,
        ],
    )
}

#[inline]
pub fn sigaction(cpu: &Cpu, args: ARG_sigaction) -> (u64, bool) {
    let ARG_sigaction { signum, nsa, osa } = args;
    sys::syscall(
        46,
        [
            signum as u64,
            at!(cpu, VMA::new(nsa as u64), ToSize::to_size(16)),
            at!(cpu, VMA::new(osa as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn sigprocmask(cpu: &Cpu, args: ARG_sigprocmask) -> (u64, bool) {
    let ARG_sigprocmask { how, mask, omask } = args;
    sys::syscall(
        48,
        [
            how as u64,
            at!(cpu, mask, ToSize::to_size(4)),
            at!(cpu, omask, ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn getlogin(cpu: &Cpu, args: ARG_getlogin) -> (u64, bool) {
    let ARG_getlogin { namebuf, namelen } = args;
    sys::syscall(
        49,
        [
            at!(cpu, VMA::new(namebuf as u64), ToSize::to_size(namelen)),
            namelen as u64,
        ],
    )
}

#[inline]
pub fn setlogin(cpu: &Cpu, args: ARG_setlogin) -> (u64, bool) {
    let ARG_setlogin { namebuf } = args;
    sys::syscall(
        50,
        [at!(
            cpu,
            VMA::new(namebuf as u64),
            ToSize::to_size(libc::MAXPATHLEN)
        )],
    )
}

#[inline]
pub fn acct(cpu: &Cpu, args: ARG_acct) -> (u64, bool) {
    let ARG_acct { path } = args;
    sys::syscall(
        51,
        [at!(
            cpu,
            VMA::new(path as u64),
            ToSize::to_size(libc::MAXPATHLEN)
        )],
    )
}

#[inline]
pub fn sigpending(cpu: &Cpu, args: ARG_sigpending) -> (u64, bool) {
    let ARG_sigpending { osv } = args;
    sys::syscall(52, [at!(cpu, VMA::new(osv as u64), ToSize::to_size(24))])
}

#[inline]
pub fn sigaltstack(cpu: &Cpu, args: ARG_sigaltstack) -> (u64, bool) {
    let ARG_sigaltstack { nss, oss } = args;
    sys::syscall(
        53,
        [
            at!(cpu, VMA::new(nss as u64), ToSize::to_size(24)),
            at!(cpu, VMA::new(oss as u64), ToSize::to_size(24)),
        ],
    )
}

#[inline]
pub fn ioctl(cpu: &Cpu, args: ARG_ioctl) -> (u64, bool) {
    todo!("ioctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn reboot(cpu: &Cpu, args: ARG_reboot) -> (u64, bool) {
    let ARG_reboot { opt, msg } = args;
    sys::syscall(
        55,
        [
            opt as u64,
            at!(cpu, VMA::new(msg as u64), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn revoke(cpu: &Cpu, args: ARG_revoke) -> (u64, bool) {
    let ARG_revoke { path } = args;
    sys::syscall(
        56,
        [at!(
            cpu,
            VMA::new(path as u64),
            ToSize::to_size(libc::MAXPATHLEN)
        )],
    )
}

#[inline]
pub fn symlink(cpu: &Cpu, args: ARG_symlink) -> (u64, bool) {
    let ARG_symlink { path, link } = args;
    sys::syscall(
        57,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(
                cpu,
                VMA::new(link as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
        ],
    )
}

#[inline]
pub fn readlink(cpu: &Cpu, args: ARG_readlink) -> (u64, bool) {
    let ARG_readlink { path, buf, count } = args;
    sys::syscall(
        58,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(count)),
            count as u64,
        ],
    )
}

#[inline]
pub fn execve(cpu: &Cpu, args: ARG_execve) -> (u64, bool) {
    todo!("execve({args:?}): {cpu:#?}");
}

#[inline]
pub fn chroot(cpu: &Cpu, args: ARG_chroot) -> (u64, bool) {
    let ARG_chroot { path } = args;
    sys::syscall(
        61,
        [at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn msync(cpu: &Cpu, args: ARG_msync) -> (u64, bool) {
    todo!("msync({args:?}): {cpu:#?}");
}

#[inline]
pub fn oslog_coproc_reg(cpu: &Cpu, args: ARG_oslog_coproc_reg) -> (u64, bool) {
    let ARG_oslog_coproc_reg {
        uuid,
        file_path,
        file_path_len,
    } = args;
    sys::syscall(
        67,
        [
            at!(cpu, uuid.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, file_path.vma(), ToSize::to_size(file_path_len)),
            file_path_len as u64,
        ],
    )
}

#[inline]
pub fn oslog_coproc(cpu: &Cpu, args: ARG_oslog_coproc) -> (u64, bool) {
    let ARG_oslog_coproc {
        buff,
        buff_len,
        r#type,
        uuid,
        timestamp,
        offset,
        stream_log,
    } = args;
    sys::syscall(
        68,
        [
            at!(cpu, VMA::new(buff as u64), ToSize::to_size(buff_len)),
            buff_len,
            r#type as u64,
            at!(cpu, uuid.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            timestamp,
            offset as u64,
            stream_log as u64,
        ],
    )
}

#[inline]
pub fn munmap(cpu: &Cpu, args: ARG_munmap) -> (u64, bool) {
    todo!("munmap({args:?}): {cpu:#?}");
}

#[inline]
pub fn mprotect(cpu: &Cpu, args: ARG_mprotect) -> (u64, bool) {
    todo!("mprotect({args:?}): {cpu:#?}");
}

#[inline]
pub fn madvise(cpu: &Cpu, args: ARG_madvise) -> (u64, bool) {
    todo!("madvise({args:?}): {cpu:#?}");
}

#[inline]
pub fn mincore(cpu: &Cpu, args: ARG_mincore) -> (u64, bool) {
    todo!("mincore({args:?}): {cpu:#?}");
}

#[inline]
pub fn getgroups(cpu: &Cpu, args: ARG_getgroups) -> (u64, bool) {
    let ARG_getgroups { gidsetsize, gidset } = args;
    sys::syscall(
        79,
        [
            gidsetsize as u64,
            at!(
                cpu,
                VMA::new(gidset as u64),
                ToSize::to_size(gidsetsize * 4)
            ),
        ],
    )
}

#[inline]
pub fn setgroups(cpu: &Cpu, args: ARG_setgroups) -> (u64, bool) {
    let ARG_setgroups { gidsetsize, gidset } = args;
    sys::syscall(
        80,
        [
            gidsetsize as u64,
            at!(
                cpu,
                VMA::new(gidset as u64),
                ToSize::to_size(gidsetsize * 4)
            ),
        ],
    )
}

#[inline]
pub fn setitimer(cpu: &Cpu, args: ARG_setitimer) -> (u64, bool) {
    let ARG_setitimer { which, itv, oitv } = args;
    sys::syscall(
        83,
        [
            which as u64,
            at!(cpu, VMA::new(itv as u64), ToSize::to_size(32)),
            at!(cpu, VMA::new(oitv as u64), ToSize::to_size(32)),
        ],
    )
}

#[inline]
pub fn getitimer(cpu: &Cpu, args: ARG_getitimer) -> (u64, bool) {
    let ARG_getitimer { which, itv } = args;
    sys::syscall(
        86,
        [
            which as u64,
            at!(cpu, VMA::new(itv as u64), ToSize::to_size(32)),
        ],
    )
}

#[inline]
pub fn sys_fcntl(cpu: &Cpu, args: ARG_sys_fcntl) -> (u64, bool) {
    todo!("sys_fcntl({args:?}): {cpu:#?}");
}

#[inline]
pub fn select(cpu: &Cpu, args: ARG_select) -> (u64, bool) {
    todo!("select({args:?}): {cpu:#?}");
}

#[inline]
pub fn connect(cpu: &Cpu, args: ARG_connect) -> (u64, bool) {
    let ARG_connect { s, name, namelen } = args;
    sys::syscall(
        98,
        [
            s as u64,
            at!(cpu, name, ToSize::to_size(namelen)),
            namelen as u64,
        ],
    )
}

#[inline]
pub fn bind(cpu: &Cpu, args: ARG_bind) -> (u64, bool) {
    let ARG_bind { s, name, namelen } = args;
    sys::syscall(
        104,
        [
            s as u64,
            at!(cpu, name, ToSize::to_size(namelen)),
            namelen as u64,
        ],
    )
}

#[inline]
pub fn setsockopt(cpu: &Cpu, args: ARG_setsockopt) -> (u64, bool) {
    let ARG_setsockopt {
        s,
        level,
        name,
        val,
        valsize,
    } = args;
    sys::syscall(
        105,
        [
            s as u64,
            level as u64,
            name as u64,
            at!(cpu, val, ToSize::to_size(valsize)),
            valsize as u64,
        ],
    )
}

#[inline]
pub fn gettimeofday(cpu: &Cpu, args: ARG_gettimeofday) -> (u64, bool) {
    let ARG_gettimeofday {
        tp,
        tzp,
        mach_absolute_time,
    } = args;
    sys::syscall(
        116,
        [
            at!(cpu, VMA::new(tp as u64), ToSize::to_size(16)),
            at!(cpu, VMA::new(tzp as u64), ToSize::to_size(8)),
            at!(cpu, VMA::new(mach_absolute_time as u64), ToSize::to_size(8)),
        ],
    )
}

#[inline]
pub fn getrusage(cpu: &Cpu, args: ARG_getrusage) -> (u64, bool) {
    let ARG_getrusage { who, rusage } = args;
    sys::syscall(
        117,
        [
            who as u64,
            at!(cpu, VMA::new(rusage as u64), ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn getsockopt(cpu: &Cpu, args: ARG_getsockopt) -> (u64, bool) {
    todo!("getsockopt({args:?}): {cpu:#?}");
}

#[inline]
pub fn readv(cpu: &Cpu, args: ARG_readv) -> (u64, bool) {
    todo!("readv({args:?}): {cpu:#?}");
}

#[inline]
pub fn writev(cpu: &Cpu, args: ARG_writev) -> (u64, bool) {
    todo!("writev({args:?}): {cpu:#?}");
}

#[inline]
pub fn settimeofday(cpu: &Cpu, args: ARG_settimeofday) -> (u64, bool) {
    let ARG_settimeofday { tv, tzp } = args;
    sys::syscall(
        122,
        [
            at!(cpu, VMA::new(tv as u64), ToSize::to_size(16)),
            at!(cpu, VMA::new(tzp as u64), ToSize::to_size(8)),
        ],
    )
}

#[inline]
pub fn rename(cpu: &Cpu, args: ARG_rename) -> (u64, bool) {
    let ARG_rename { from, to } = args;
    sys::syscall(
        128,
        [
            at!(
                cpu,
                VMA::new(from as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(to as u64), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn mkfifo(cpu: &Cpu, args: ARG_mkfifo) -> (u64, bool) {
    let ARG_mkfifo { path, mode } = args;
    sys::syscall(
        132,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
        ],
    )
}

#[inline]
pub fn sendto(cpu: &Cpu, args: ARG_sendto) -> (u64, bool) {
    let ARG_sendto {
        s,
        buf,
        len,
        flags,
        to,
        tolen,
    } = args;
    sys::syscall(
        133,
        [
            s as u64,
            at!(cpu, buf, ToSize::to_size(len)),
            len as u64,
            flags as u64,
            at!(cpu, to, ToSize::to_size(tolen)),
            tolen as u64,
        ],
    )
}

#[inline]
pub fn socketpair(cpu: &Cpu, args: ARG_socketpair) -> (u64, bool) {
    let ARG_socketpair {
        domain,
        r#type,
        protocol,
        rsv,
    } = args;
    sys::syscall(
        135,
        [
            domain as u64,
            r#type as u64,
            protocol as u64,
            at!(cpu, VMA::new(rsv as u64), ToSize::to_size(2 * 4)),
        ],
    )
}

#[inline]
pub fn mkdir(cpu: &Cpu, args: ARG_mkdir) -> (u64, bool) {
    let ARG_mkdir { path, mode } = args;
    sys::syscall(
        136,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
        ],
    )
}

#[inline]
pub fn rmdir(cpu: &Cpu, args: ARG_rmdir) -> (u64, bool) {
    let ARG_rmdir { path } = args;
    sys::syscall(
        137,
        [at!(
            cpu,
            VMA::new(path as u64),
            ToSize::to_size(libc::MAXPATHLEN)
        )],
    )
}

#[inline]
pub fn utimes(cpu: &Cpu, args: ARG_utimes) -> (u64, bool) {
    let ARG_utimes { path, tptr } = args;
    sys::syscall(
        138,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(tptr as u64), ToSize::to_size(2 * 16)),
        ],
    )
}

#[inline]
pub fn futimes(cpu: &Cpu, args: ARG_futimes) -> (u64, bool) {
    let ARG_futimes { fd, tptr } = args;
    sys::syscall(
        139,
        [
            fd as u64,
            at!(cpu, VMA::new(tptr as u64), ToSize::to_size(2 * 16)),
        ],
    )
}

#[inline]
pub fn adjtime(cpu: &Cpu, args: ARG_adjtime) -> (u64, bool) {
    let ARG_adjtime { delta, olddelta } = args;
    sys::syscall(
        140,
        [
            at!(cpu, VMA::new(delta as u64), ToSize::to_size(16)),
            at!(cpu, VMA::new(olddelta as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn gethostuuid(cpu: &Cpu, args: ARG_gethostuuid) -> (u64, bool) {
    let ARG_gethostuuid { uuid_buf, timeoutp } = args;
    sys::syscall(
        142,
        [
            at!(cpu, VMA::new(uuid_buf as u64), ToSize::to_size(16)),
            at!(cpu, VMA::new(timeoutp as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn pread(cpu: &Cpu, args: ARG_pread) -> (u64, bool) {
    let ARG_pread {
        fd,
        buf,
        nbyte,
        offset,
    } = args;
    sys::syscall(
        153,
        [
            fd as u64,
            at!(cpu, buf, ToSize::to_size(nbyte)),
            nbyte as u64,
            offset as u64,
        ],
    )
}

#[inline]
pub fn pwrite(cpu: &Cpu, args: ARG_pwrite) -> (u64, bool) {
    let ARG_pwrite {
        fd,
        buf,
        nbyte,
        offset,
    } = args;
    sys::syscall(
        154,
        [
            fd as u64,
            at!(cpu, buf, ToSize::to_size(nbyte)),
            nbyte as u64,
            offset as u64,
        ],
    )
}

#[inline]
pub fn nfssvc(cpu: &Cpu, args: ARG_nfssvc) -> (u64, bool) {
    todo!("nfssvc({args:?}): {cpu:#?}");
}

#[inline]
pub fn statfs(cpu: &Cpu, args: ARG_statfs) -> (u64, bool) {
    let ARG_statfs { path, buf } = args;
    sys::syscall(
        157,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(2168)),
        ],
    )
}

#[inline]
pub fn fstatfs(cpu: &Cpu, args: ARG_fstatfs) -> (u64, bool) {
    let ARG_fstatfs { fd, buf } = args;
    sys::syscall(
        158,
        [
            fd as u64,
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(2168)),
        ],
    )
}

#[inline]
pub fn unmount(cpu: &Cpu, args: ARG_unmount) -> (u64, bool) {
    let ARG_unmount { path, flags } = args;
    sys::syscall(
        159,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
        ],
    )
}

#[inline]
pub fn getfh(cpu: &Cpu, args: ARG_getfh) -> (u64, bool) {
    let ARG_getfh { fname, fhp } = args;
    sys::syscall(
        161,
        [
            at!(
                cpu,
                VMA::new(fname as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(fhp as u64), ToSize::to_size(132)),
        ],
    )
}

#[inline]
pub fn quotactl(cpu: &Cpu, args: ARG_quotactl) -> (u64, bool) {
    todo!("quotactl({args:?}): {cpu:#?}");
}

#[inline]
pub fn mount(cpu: &Cpu, args: ARG_mount) -> (u64, bool) {
    todo!("mount({args:?}): {cpu:#?}");
}

#[inline]
pub fn csops(cpu: &Cpu, args: ARG_csops) -> (u64, bool) {
    todo!("csops({args:?}): {cpu:#?}");
}

#[inline]
pub fn csops_audittoken(cpu: &Cpu, args: ARG_csops_audittoken) -> (u64, bool) {
    todo!("csops_audittoken({args:?}): {cpu:#?}");
}

#[inline]
pub fn waitid(cpu: &Cpu, args: ARG_waitid) -> (u64, bool) {
    let ARG_waitid {
        idtype,
        id,
        infop,
        options,
    } = args;
    sys::syscall(
        173,
        [
            idtype as u64,
            id as u64,
            at!(cpu, VMA::new(infop as u64), ToSize::to_size(104)),
            options as u64,
        ],
    )
}

#[inline]
pub fn kdebug_typefilter(cpu: &Cpu, args: ARG_kdebug_typefilter) -> (u64, bool) {
    todo!("kdebug_typefilter({args:?}): {cpu:#?}");
}

#[inline]
pub fn kdebug_trace_string(cpu: &Cpu, args: ARG_kdebug_trace_string) -> (u64, bool) {
    let ARG_kdebug_trace_string {
        debugid,
        str_id,
        str,
    } = args;
    sys::syscall(
        178,
        [
            debugid as u64,
            str_id,
            at!(cpu, str.vma(), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn sigreturn(cpu: &Cpu, args: ARG_sigreturn) -> (u64, bool) {
    todo!("sigreturn({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_panic_with_data(cpu: &Cpu, args: ARG_sys_panic_with_data) -> (u64, bool) {
    let ARG_sys_panic_with_data {
        uuid,
        addr,
        len,
        flags,
        msg,
    } = args;
    sys::syscall(
        185,
        [
            at!(cpu, VMA::new(uuid as u64), ToSize::to_size(16)),
            at!(cpu, VMA::new(addr as u64), ToSize::to_size(len)),
            len as u64,
            flags as u64,
            at!(cpu, msg.vma(), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn thread_selfcounts(cpu: &Cpu, args: ARG_thread_selfcounts) -> (u64, bool) {
    let ARG_thread_selfcounts { kind, buf, size } = args;
    sys::syscall(
        186,
        [
            kind as u64,
            at!(cpu, buf, ToSize::to_size(size)),
            size as u64,
        ],
    )
}

#[inline]
pub fn stat(cpu: &Cpu, args: ARG_stat) -> (u64, bool) {
    let ARG_stat { path, ub } = args;
    sys::syscall(
        188,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, ub, ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn sys_fstat(cpu: &Cpu, args: ARG_sys_fstat) -> (u64, bool) {
    let ARG_sys_fstat { fd, ub } = args;
    sys::syscall(189, [fd as u64, at!(cpu, ub, ToSize::to_size(144))])
}

#[inline]
pub fn lstat(cpu: &Cpu, args: ARG_lstat) -> (u64, bool) {
    let ARG_lstat { path, ub } = args;
    sys::syscall(
        190,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, ub, ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn pathconf(cpu: &Cpu, args: ARG_pathconf) -> (u64, bool) {
    let ARG_pathconf { path, name } = args;
    sys::syscall(
        191,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            name as u64,
        ],
    )
}

#[inline]
pub fn getrlimit(cpu: &Cpu, args: ARG_getrlimit) -> (u64, bool) {
    let ARG_getrlimit { which, rlp } = args;
    sys::syscall(
        194,
        [
            which as u64,
            at!(cpu, VMA::new(rlp as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn setrlimit(cpu: &Cpu, args: ARG_setrlimit) -> (u64, bool) {
    let ARG_setrlimit { which, rlp } = args;
    sys::syscall(
        195,
        [
            which as u64,
            at!(cpu, VMA::new(rlp as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn getdirentries(cpu: &Cpu, args: ARG_getdirentries) -> (u64, bool) {
    let ARG_getdirentries {
        fd,
        buf,
        count,
        basep,
    } = args;
    sys::syscall(
        196,
        [
            fd as u64,
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(count)),
            count as u64,
            at!(cpu, VMA::new(basep as u64), ToSize::to_size(8)),
        ],
    )
}

#[inline]
pub fn mmap(_cpu: &Cpu, _args: ARG_mmap) -> (i64, bool) {
    todo!()
}

#[inline]
pub fn truncate(cpu: &Cpu, args: ARG_truncate) -> (u64, bool) {
    let ARG_truncate { path, length } = args;
    sys::syscall(
        200,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            length as u64,
        ],
    )
}

#[inline]
pub fn sysctl(cpu: &Cpu, args: ARG_sysctl) -> (u64, bool) {
    todo!("sysctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn mlock(cpu: &Cpu, args: ARG_mlock) -> (u64, bool) {
    todo!("mlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn munlock(cpu: &Cpu, args: ARG_munlock) -> (u64, bool) {
    todo!("munlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn undelete(cpu: &Cpu, args: ARG_undelete) -> (u64, bool) {
    let ARG_undelete { path } = args;
    sys::syscall(
        205,
        [at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn open_dprotected_np(cpu: &Cpu, args: ARG_open_dprotected_np) -> (u64, bool) {
    let ARG_open_dprotected_np {
        path,
        flags,
        class,
        dpflags,
        mode,
    } = args;
    sys::syscall(
        216,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
            class as u64,
            dpflags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn fsgetpath_ext(cpu: &Cpu, args: ARG_fsgetpath_ext) -> (u64, bool) {
    let ARG_fsgetpath_ext {
        buf,
        bufsize,
        fsid,
        objid,
        options,
    } = args;
    sys::syscall(
        217,
        [
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
            at!(cpu, fsid, ToSize::to_size(8)),
            objid,
            options as u64,
        ],
    )
}

#[inline]
pub fn openat_dprotected_np(cpu: &Cpu, args: ARG_openat_dprotected_np) -> (u64, bool) {
    let ARG_openat_dprotected_np {
        fd,
        path,
        flags,
        class,
        dpflags,
        mode,
        authfd,
    } = args;
    sys::syscall(
        218,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
            class as u64,
            dpflags as u64,
            mode as u64,
            authfd as u64,
        ],
    )
}

#[inline]
pub fn getattrlist(cpu: &Cpu, args: ARG_getattrlist) -> (u64, bool) {
    todo!("getattrlist({args:?}): {cpu:#?}");
}

#[inline]
pub fn setattrlist(cpu: &Cpu, args: ARG_setattrlist) -> (u64, bool) {
    todo!("setattrlist({args:?}): {cpu:#?}");
}

#[inline]
pub fn getdirentriesattr(cpu: &Cpu, args: ARG_getdirentriesattr) -> (u64, bool) {
    let ARG_getdirentriesattr {
        fd,
        alist,
        buffer,
        buffersize,
        count,
        basep,
        newstate,
        options,
    } = args;
    sys::syscall(
        222,
        [
            fd as u64,
            at!(cpu, VMA::new(alist as u64), ToSize::to_size(24)),
            at!(cpu, VMA::new(buffer as u64), ToSize::to_size(buffersize)),
            buffersize as u64,
            at!(cpu, VMA::new(count as u64), ToSize::to_size(8)),
            at!(cpu, VMA::new(basep as u64), ToSize::to_size(8)),
            at!(cpu, VMA::new(newstate as u64), ToSize::to_size(8)),
            options,
        ],
    )
}

#[inline]
pub fn exchangedata(cpu: &Cpu, args: ARG_exchangedata) -> (u64, bool) {
    let ARG_exchangedata {
        path1,
        path2,
        options,
    } = args;
    sys::syscall(
        223,
        [
            at!(cpu, path1.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, path2.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            options,
        ],
    )
}

#[inline]
pub fn searchfs(cpu: &Cpu, args: ARG_searchfs) -> (u64, bool) {
    let ARG_searchfs {
        path,
        searchblock,
        nummatches,
        scriptcode,
        options,
        state,
    } = args;
    sys::syscall(
        225,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, VMA::new(searchblock as u64), ToSize::to_size(104)),
            at!(cpu, VMA::new(nummatches as u64), ToSize::to_size(4)),
            scriptcode as u64,
            options as u64,
            at!(cpu, VMA::new(state as u64), ToSize::to_size(556)),
        ],
    )
}

#[inline]
pub fn delete(cpu: &Cpu, args: ARG_delete) -> (u64, bool) {
    let ARG_delete { path } = args;
    sys::syscall(
        226,
        [at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn copyfile(cpu: &Cpu, args: ARG_copyfile) -> (u64, bool) {
    let ARG_copyfile {
        from,
        to,
        mode,
        flags,
    } = args;
    sys::syscall(
        227,
        [
            at!(
                cpu,
                VMA::new(from as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(to as u64), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
            flags as u64,
        ],
    )
}

#[inline]
pub fn fgetattrlist(cpu: &Cpu, args: ARG_fgetattrlist) -> (u64, bool) {
    todo!("fgetattrlist({args:?}): {cpu:#?}");
}

#[inline]
pub fn fsetattrlist(cpu: &Cpu, args: ARG_fsetattrlist) -> (u64, bool) {
    todo!("fsetattrlist({args:?}): {cpu:#?}");
}

#[inline]
pub fn poll(cpu: &Cpu, args: ARG_poll) -> (u64, bool) {
    let ARG_poll { fds, nfds, timeout } = args;
    sys::syscall(
        230,
        [
            at!(cpu, VMA::new(fds as u64), ToSize::to_size(nfds * 8)),
            nfds as u64,
            timeout as u64,
        ],
    )
}

#[inline]
pub fn getxattr(cpu: &Cpu, args: ARG_getxattr) -> (u64, bool) {
    let ARG_getxattr {
        path,
        attrname,
        value,
        size,
        position,
        options,
    } = args;
    sys::syscall(
        234,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, attrname.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, value, ToSize::to_size(size)),
            size as u64,
            position as u64,
            options as u64,
        ],
    )
}

#[inline]
pub fn fgetxattr(cpu: &Cpu, args: ARG_fgetxattr) -> (u64, bool) {
    let ARG_fgetxattr {
        fd,
        attrname,
        value,
        size,
        position,
        options,
    } = args;
    sys::syscall(
        235,
        [
            fd as u64,
            at!(cpu, attrname.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, value, ToSize::to_size(size)),
            size as u64,
            position as u64,
            options as u64,
        ],
    )
}

#[inline]
pub fn setxattr(cpu: &Cpu, args: ARG_setxattr) -> (u64, bool) {
    let ARG_setxattr {
        path,
        attrname,
        value,
        size,
        position,
        options,
    } = args;
    sys::syscall(
        236,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, attrname.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, value, ToSize::to_size(size)),
            size as u64,
            position as u64,
            options as u64,
        ],
    )
}

#[inline]
pub fn fsetxattr(cpu: &Cpu, args: ARG_fsetxattr) -> (u64, bool) {
    let ARG_fsetxattr {
        fd,
        attrname,
        value,
        size,
        position,
        options,
    } = args;
    sys::syscall(
        237,
        [
            fd as u64,
            at!(cpu, attrname.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, value, ToSize::to_size(size)),
            size as u64,
            position as u64,
            options as u64,
        ],
    )
}

#[inline]
pub fn removexattr(cpu: &Cpu, args: ARG_removexattr) -> (u64, bool) {
    let ARG_removexattr {
        path,
        attrname,
        options,
    } = args;
    sys::syscall(
        238,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, attrname.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            options as u64,
        ],
    )
}

#[inline]
pub fn fremovexattr(cpu: &Cpu, args: ARG_fremovexattr) -> (u64, bool) {
    let ARG_fremovexattr {
        fd,
        attrname,
        options,
    } = args;
    sys::syscall(
        239,
        [
            fd as u64,
            at!(cpu, attrname.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            options as u64,
        ],
    )
}

#[inline]
pub fn listxattr(cpu: &Cpu, args: ARG_listxattr) -> (u64, bool) {
    let ARG_listxattr {
        path,
        namebuf,
        bufsize,
        options,
    } = args;
    sys::syscall(
        240,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, namebuf, ToSize::to_size(bufsize)),
            bufsize as u64,
            options as u64,
        ],
    )
}

#[inline]
pub fn flistxattr(cpu: &Cpu, args: ARG_flistxattr) -> (u64, bool) {
    let ARG_flistxattr {
        fd,
        namebuf,
        bufsize,
        options,
    } = args;
    sys::syscall(
        241,
        [
            fd as u64,
            at!(cpu, namebuf, ToSize::to_size(bufsize)),
            bufsize as u64,
            options as u64,
        ],
    )
}

#[inline]
pub fn fsctl(cpu: &Cpu, args: ARG_fsctl) -> (u64, bool) {
    todo!("fsctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn initgroups(cpu: &Cpu, args: ARG_initgroups) -> (u64, bool) {
    let ARG_initgroups {
        gidsetsize,
        gidset,
        gmuid,
    } = args;
    sys::syscall(
        243,
        [
            gidsetsize as u64,
            at!(
                cpu,
                VMA::new(gidset as u64),
                ToSize::to_size(gidsetsize * 4)
            ),
            gmuid as u64,
        ],
    )
}

#[inline]
pub fn posix_spawn(cpu: &Cpu, args: ARG_posix_spawn) -> (u64, bool) {
    todo!("posix_spawn({args:?}): {cpu:#?}");
}

#[inline]
pub fn ffsctl(cpu: &Cpu, args: ARG_ffsctl) -> (u64, bool) {
    todo!("ffsctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn fhopen(cpu: &Cpu, args: ARG_fhopen) -> (u64, bool) {
    let ARG_fhopen { u_fhp, flags } = args;
    sys::syscall(
        248,
        [
            at!(cpu, VMA::new(u_fhp as u64), ToSize::to_size(132)),
            flags as u64,
        ],
    )
}

#[inline]
pub fn minherit(cpu: &Cpu, args: ARG_minherit) -> (u64, bool) {
    todo!("minherit({args:?}): {cpu:#?}");
}

#[inline]
pub fn semctl(_cpu: &Cpu, _args: ARG_semctl) -> (i64, bool) {
    todo!()
}

#[inline]
pub fn semop(cpu: &Cpu, args: ARG_semop) -> (u64, bool) {
    let ARG_semop { semid, sops, nsops } = args;
    sys::syscall(
        256,
        [
            semid as u64,
            at!(cpu, VMA::new(sops as u64), ToSize::to_size(nsops * 6)),
            nsops as u64,
        ],
    )
}

#[inline]
pub fn msgctl(cpu: &Cpu, args: ARG_msgctl) -> (u64, bool) {
    todo!("msgctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn msgsnd(cpu: &Cpu, args: ARG_msgsnd) -> (u64, bool) {
    let ARG_msgsnd {
        msqid,
        msgp,
        msgsz,
        msgflg,
    } = args;
    sys::syscall(
        260,
        [
            msqid as u64,
            at!(cpu, VMA::new(msgp as u64), ToSize::to_size(8 + msgsz)),
            msgsz as u64,
            msgflg as u64,
        ],
    )
}

#[inline]
pub fn msgrcv(cpu: &Cpu, args: ARG_msgrcv) -> (u64, bool) {
    let ARG_msgrcv {
        msqid,
        msgp,
        msgsz,
        msgtyp,
        msgflg,
    } = args;
    sys::syscall(
        261,
        [
            msqid as u64,
            at!(cpu, VMA::new(msgp as u64), ToSize::to_size(8 + msgsz)),
            msgsz as u64,
            msgtyp as u64,
            msgflg as u64,
        ],
    )
}

#[inline]
pub fn shmat(_cpu: &Cpu, _args: ARG_shmat) -> (i64, bool) {
    todo!()
}

#[inline]
pub fn shmctl(cpu: &Cpu, args: ARG_shmctl) -> (u64, bool) {
    todo!("shmctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn shmdt(cpu: &Cpu, args: ARG_shmdt) -> (u64, bool) {
    todo!("shmdt({args:?}): {cpu:#?}");
}

#[inline]
pub fn shm_open(cpu: &Cpu, args: ARG_shm_open) -> (u64, bool) {
    let ARG_shm_open { name, oflag, mode } = args;
    sys::syscall(
        266,
        [
            at!(cpu, name.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            oflag as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn shm_unlink(cpu: &Cpu, args: ARG_shm_unlink) -> (u64, bool) {
    let ARG_shm_unlink { name } = args;
    sys::syscall(
        267,
        [at!(cpu, name.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn sem_open(_cpu: &Cpu, _args: ARG_sem_open) -> (i64, bool) {
    todo!()
}

#[inline]
pub fn sem_close(cpu: &Cpu, args: ARG_sem_close) -> (u64, bool) {
    todo!("sem_close({args:?}): {cpu:#?}");
}

#[inline]
pub fn sem_unlink(cpu: &Cpu, args: ARG_sem_unlink) -> (u64, bool) {
    let ARG_sem_unlink { name } = args;
    sys::syscall(
        270,
        [at!(cpu, name.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn sem_wait(cpu: &Cpu, args: ARG_sem_wait) -> (u64, bool) {
    todo!("sem_wait({args:?}): {cpu:#?}");
}

#[inline]
pub fn sem_trywait(cpu: &Cpu, args: ARG_sem_trywait) -> (u64, bool) {
    todo!("sem_trywait({args:?}): {cpu:#?}");
}

#[inline]
pub fn sem_post(cpu: &Cpu, args: ARG_sem_post) -> (u64, bool) {
    todo!("sem_post({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_sysctlbyname(cpu: &Cpu, args: ARG_sys_sysctlbyname) -> (u64, bool) {
    todo!("sys_sysctlbyname({args:?}): {cpu:#?}");
}

#[inline]
pub fn open_extended(cpu: &Cpu, args: ARG_open_extended) -> (u64, bool) {
    todo!("open_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn umask_extended(cpu: &Cpu, args: ARG_umask_extended) -> (u64, bool) {
    todo!("umask_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn stat_extended(cpu: &Cpu, args: ARG_stat_extended) -> (u64, bool) {
    todo!("stat_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn lstat_extended(cpu: &Cpu, args: ARG_lstat_extended) -> (u64, bool) {
    todo!("lstat_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_fstat_extended(cpu: &Cpu, args: ARG_sys_fstat_extended) -> (u64, bool) {
    todo!("sys_fstat_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn chmod_extended(cpu: &Cpu, args: ARG_chmod_extended) -> (u64, bool) {
    todo!("chmod_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn fchmod_extended(cpu: &Cpu, args: ARG_fchmod_extended) -> (u64, bool) {
    todo!("fchmod_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn access_extended(cpu: &Cpu, args: ARG_access_extended) -> (u64, bool) {
    let ARG_access_extended {
        entries,
        size,
        results,
        uid,
    } = args;
    sys::syscall(
        284,
        [
            at!(cpu, entries, ToSize::to_size(size)),
            size as u64,
            at!(cpu, results, ToSize::to_size(size)),
            uid as u64,
        ],
    )
}

#[inline]
pub fn gettid(cpu: &Cpu, args: ARG_gettid) -> (u64, bool) {
    let ARG_gettid { uidp, gidp } = args;
    sys::syscall(
        286,
        [
            at!(cpu, VMA::new(uidp as u64), ToSize::to_size(4)),
            at!(cpu, VMA::new(gidp as u64), ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn setsgroups(_cpu: &Cpu, _args: ARG_setsgroups) -> (i64, bool) {
    (libc::ENOTSUP as i64, false)
}

#[inline]
pub fn getsgroups(_cpu: &Cpu, _args: ARG_getsgroups) -> (i64, bool) {
    (libc::ENOTSUP as i64, false)
}

#[inline]
pub fn setwgroups(_cpu: &Cpu, _args: ARG_setwgroups) -> (i64, bool) {
    (libc::ENOTSUP as i64, false)
}

#[inline]
pub fn getwgroups(_cpu: &Cpu, _args: ARG_getwgroups) -> (i64, bool) {
    (libc::ENOTSUP as i64, false)
}

#[inline]
pub fn mkfifo_extended(cpu: &Cpu, args: ARG_mkfifo_extended) -> (u64, bool) {
    todo!("mkfifo_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn mkdir_extended(cpu: &Cpu, args: ARG_mkdir_extended) -> (u64, bool) {
    todo!("mkdir_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn identitysvc(cpu: &Cpu, args: ARG_identitysvc) -> (u64, bool) {
    todo!("identitysvc({args:?}): {cpu:#?}");
}

#[inline]
pub fn shared_region_check_np(cpu: &Cpu, args: ARG_shared_region_check_np) -> (u64, bool) {
    let ARG_shared_region_check_np { start_address } = args;
    sys::syscall(
        294,
        [at!(cpu, VMA::new(start_address as u64), ToSize::to_size(8))],
    )
}

#[inline]
pub fn vm_pressure_monitor(cpu: &Cpu, args: ARG_vm_pressure_monitor) -> (u64, bool) {
    let ARG_vm_pressure_monitor {
        wait_for_pressure,
        nsecs_monitored,
        pages_reclaimed,
    } = args;
    sys::syscall(
        296,
        [
            wait_for_pressure as u64,
            nsecs_monitored as u64,
            at!(cpu, VMA::new(pages_reclaimed as u64), ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn psynch_rw_longrdlock(cpu: &Cpu, args: ARG_psynch_rw_longrdlock) -> (u64, bool) {
    todo!("psynch_rw_longrdlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_yieldwrlock(cpu: &Cpu, args: ARG_psynch_rw_yieldwrlock) -> (u64, bool) {
    todo!("psynch_rw_yieldwrlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_downgrade(cpu: &Cpu, args: ARG_psynch_rw_downgrade) -> (u64, bool) {
    todo!("psynch_rw_downgrade({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_upgrade(cpu: &Cpu, args: ARG_psynch_rw_upgrade) -> (u64, bool) {
    todo!("psynch_rw_upgrade({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_mutexwait(cpu: &Cpu, args: ARG_psynch_mutexwait) -> (u64, bool) {
    todo!("psynch_mutexwait({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_mutexdrop(cpu: &Cpu, args: ARG_psynch_mutexdrop) -> (u64, bool) {
    todo!("psynch_mutexdrop({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_cvbroad(cpu: &Cpu, args: ARG_psynch_cvbroad) -> (u64, bool) {
    todo!("psynch_cvbroad({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_cvsignal(cpu: &Cpu, args: ARG_psynch_cvsignal) -> (u64, bool) {
    todo!("psynch_cvsignal({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_cvwait(cpu: &Cpu, args: ARG_psynch_cvwait) -> (u64, bool) {
    todo!("psynch_cvwait({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_rdlock(cpu: &Cpu, args: ARG_psynch_rw_rdlock) -> (u64, bool) {
    todo!("psynch_rw_rdlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_wrlock(cpu: &Cpu, args: ARG_psynch_rw_wrlock) -> (u64, bool) {
    todo!("psynch_rw_wrlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_unlock(cpu: &Cpu, args: ARG_psynch_rw_unlock) -> (u64, bool) {
    todo!("psynch_rw_unlock({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_rw_unlock2(cpu: &Cpu, args: ARG_psynch_rw_unlock2) -> (u64, bool) {
    todo!("psynch_rw_unlock2({args:?}): {cpu:#?}");
}

#[inline]
pub fn psynch_cvclrprepost(cpu: &Cpu, args: ARG_psynch_cvclrprepost) -> (u64, bool) {
    todo!("psynch_cvclrprepost({args:?}): {cpu:#?}");
}

#[inline]
pub fn aio_fsync(cpu: &Cpu, args: ARG_aio_fsync) -> (u64, bool) {
    let ARG_aio_fsync { op, aiocbp } = args;
    sys::syscall(313, [op as u64, at!(cpu, aiocbp, ToSize::to_size(80))])
}

#[inline]
pub fn aio_return(cpu: &Cpu, args: ARG_aio_return) -> (u64, bool) {
    todo!("aio_return({args:?}): {cpu:#?}");
}

#[inline]
pub fn aio_suspend(cpu: &Cpu, args: ARG_aio_suspend) -> (u64, bool) {
    let ARG_aio_suspend {
        aiocblist,
        nent,
        timeoutp,
    } = args;
    sys::syscall(
        315,
        [
            at!(cpu, aiocblist, ToSize::to_size(nent * 8)),
            nent as u64,
            at!(cpu, timeoutp, ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn aio_cancel(cpu: &Cpu, args: ARG_aio_cancel) -> (u64, bool) {
    let ARG_aio_cancel { fd, aiocbp } = args;
    sys::syscall(316, [fd as u64, at!(cpu, aiocbp, ToSize::to_size(80))])
}

#[inline]
pub fn aio_error(cpu: &Cpu, args: ARG_aio_error) -> (u64, bool) {
    todo!("aio_error({args:?}): {cpu:#?}");
}

#[inline]
pub fn aio_read(cpu: &Cpu, args: ARG_aio_read) -> (u64, bool) {
    todo!("aio_read({args:?}): {cpu:#?}");
}

#[inline]
pub fn aio_write(cpu: &Cpu, args: ARG_aio_write) -> (u64, bool) {
    todo!("aio_write({args:?}): {cpu:#?}");
}

#[inline]
pub fn lio_listio(cpu: &Cpu, args: ARG_lio_listio) -> (u64, bool) {
    let ARG_lio_listio {
        mode,
        aiocblist,
        nent,
        sigp,
    } = args;
    sys::syscall(
        320,
        [
            mode as u64,
            at!(cpu, aiocblist, ToSize::to_size(nent * 8)),
            nent as u64,
            at!(cpu, sigp, ToSize::to_size(32)),
        ],
    )
}

#[inline]
pub fn iopolicysys(cpu: &Cpu, args: ARG_iopolicysys) -> (u64, bool) {
    todo!("iopolicysys({args:?}): {cpu:#?}");
}

#[inline]
pub fn process_policy(cpu: &Cpu, args: ARG_process_policy) -> (u64, bool) {
    todo!("process_policy({args:?}): {cpu:#?}");
}

#[inline]
pub fn __pthread_sigmask(cpu: &Cpu, args: ARG___pthread_sigmask) -> (u64, bool) {
    let ARG___pthread_sigmask { how, set, oset } = args;
    sys::syscall(
        329,
        [
            how as u64,
            at!(cpu, set, ToSize::to_size(4)),
            at!(cpu, oset, ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn __sigwait(cpu: &Cpu, args: ARG___sigwait) -> (u64, bool) {
    let ARG___sigwait { set, sig } = args;
    sys::syscall(
        330,
        [
            at!(cpu, set, ToSize::to_size(4)),
            at!(cpu, sig, ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn proc_info(cpu: &Cpu, args: ARG_proc_info) -> (u64, bool) {
    todo!("proc_info({args:?}): {cpu:#?}");
}

#[inline]
pub fn sendfile(cpu: &Cpu, args: ARG_sendfile) -> (u64, bool) {
    todo!("sendfile({args:?}): {cpu:#?}");
}

#[inline]
pub fn stat64(cpu: &Cpu, args: ARG_stat64) -> (u64, bool) {
    let ARG_stat64 { path, ub } = args;
    sys::syscall(
        338,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, ub, ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn sys_fstat64(cpu: &Cpu, args: ARG_sys_fstat64) -> (u64, bool) {
    let ARG_sys_fstat64 { fd, ub } = args;
    sys::syscall(339, [fd as u64, at!(cpu, ub, ToSize::to_size(144))])
}

#[inline]
pub fn lstat64(cpu: &Cpu, args: ARG_lstat64) -> (u64, bool) {
    let ARG_lstat64 { path, ub } = args;
    sys::syscall(
        340,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, ub, ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn stat64_extended(cpu: &Cpu, args: ARG_stat64_extended) -> (u64, bool) {
    todo!("stat64_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn lstat64_extended(cpu: &Cpu, args: ARG_lstat64_extended) -> (u64, bool) {
    todo!("lstat64_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_fstat64_extended(cpu: &Cpu, args: ARG_sys_fstat64_extended) -> (u64, bool) {
    todo!("sys_fstat64_extended({args:?}): {cpu:#?}");
}

#[inline]
pub fn getdirentries64(cpu: &Cpu, args: ARG_getdirentries64) -> (u64, bool) {
    let ARG_getdirentries64 {
        fd,
        buf,
        bufsize,
        position,
    } = args;
    sys::syscall(
        344,
        [
            fd as u64,
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(bufsize)),
            bufsize as u64,
            at!(cpu, VMA::new(position as u64), ToSize::to_size(8)),
        ],
    )
}

#[inline]
pub fn statfs64(cpu: &Cpu, args: ARG_statfs64) -> (u64, bool) {
    let ARG_statfs64 { path, buf } = args;
    sys::syscall(
        345,
        [
            at!(
                cpu,
                VMA::new(path as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(2168)),
        ],
    )
}

#[inline]
pub fn fstatfs64(cpu: &Cpu, args: ARG_fstatfs64) -> (u64, bool) {
    let ARG_fstatfs64 { fd, buf } = args;
    sys::syscall(
        346,
        [
            fd as u64,
            at!(cpu, VMA::new(buf as u64), ToSize::to_size(2168)),
        ],
    )
}

#[inline]
pub fn getfsstat64(cpu: &Cpu, args: ARG_getfsstat64) -> (u64, bool) {
    let ARG_getfsstat64 {
        buf,
        bufsize,
        flags,
    } = args;
    sys::syscall(
        347,
        [
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
            flags as u64,
        ],
    )
}

#[inline]
pub fn __pthread_chdir(cpu: &Cpu, args: ARG___pthread_chdir) -> (u64, bool) {
    let ARG___pthread_chdir { path } = args;
    sys::syscall(
        348,
        [at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN))],
    )
}

#[inline]
pub fn audit(cpu: &Cpu, args: ARG_audit) -> (u64, bool) {
    let ARG_audit { record, length } = args;
    sys::syscall(
        350,
        [
            at!(cpu, VMA::new(record as u64), ToSize::to_size(length)),
            length as u64,
        ],
    )
}

#[inline]
pub fn auditon(cpu: &Cpu, args: ARG_auditon) -> (u64, bool) {
    todo!("auditon({args:?}): {cpu:#?}");
}

#[inline]
pub fn getauid(cpu: &Cpu, args: ARG_getauid) -> (u64, bool) {
    let ARG_getauid { auid } = args;
    sys::syscall(353, [at!(cpu, VMA::new(auid as u64), ToSize::to_size(4))])
}

#[inline]
pub fn setauid(cpu: &Cpu, args: ARG_setauid) -> (u64, bool) {
    let ARG_setauid { auid } = args;
    sys::syscall(354, [at!(cpu, VMA::new(auid as u64), ToSize::to_size(4))])
}

#[inline]
pub fn getaudit_addr(cpu: &Cpu, args: ARG_getaudit_addr) -> (u64, bool) {
    let ARG_getaudit_addr {
        auditinfo_addr,
        length,
    } = args;
    sys::syscall(
        357,
        [
            at!(
                cpu,
                VMA::new(auditinfo_addr as u64),
                ToSize::to_size(length)
            ),
            length as u64,
        ],
    )
}

#[inline]
pub fn setaudit_addr(cpu: &Cpu, args: ARG_setaudit_addr) -> (u64, bool) {
    let ARG_setaudit_addr {
        auditinfo_addr,
        length,
    } = args;
    sys::syscall(
        358,
        [
            at!(
                cpu,
                VMA::new(auditinfo_addr as u64),
                ToSize::to_size(length)
            ),
            length as u64,
        ],
    )
}

#[inline]
pub fn auditctl(cpu: &Cpu, args: ARG_auditctl) -> (u64, bool) {
    let ARG_auditctl { path } = args;
    sys::syscall(
        359,
        [at!(
            cpu,
            VMA::new(path as u64),
            ToSize::to_size(libc::MAXPATHLEN)
        )],
    )
}

#[inline]
pub fn bsdthread_create(_cpu: &Cpu, _args: ARG_bsdthread_create) -> (i64, bool) {
    todo!()
}

#[inline]
pub fn bsdthread_terminate(cpu: &Cpu, args: ARG_bsdthread_terminate) -> (u64, bool) {
    todo!("bsdthread_terminate({args:?}): {cpu:#?}");
}

#[inline]
pub fn kevent(cpu: &Cpu, args: ARG_kevent) -> (u64, bool) {
    let ARG_kevent {
        fd,
        changelist,
        nchanges,
        eventlist,
        nevents,
        timeout,
    } = args;
    sys::syscall(
        363,
        [
            fd as u64,
            at!(
                cpu,
                VMA::new(changelist as u64),
                ToSize::to_size(nchanges * 32)
            ),
            nchanges as u64,
            at!(
                cpu,
                VMA::new(eventlist as u64),
                ToSize::to_size(nevents * 32)
            ),
            nevents as u64,
            at!(cpu, VMA::new(timeout as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn lchown(cpu: &Cpu, args: ARG_lchown) -> (u64, bool) {
    let ARG_lchown { path, owner, group } = args;
    sys::syscall(
        364,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            owner as u64,
            group as u64,
        ],
    )
}

#[inline]
pub fn bsdthread_register(cpu: &Cpu, args: ARG_bsdthread_register) -> (u64, bool) {
    todo!("bsdthread_register({args:?}): {cpu:#?}");
}

#[inline]
pub fn workq_kernreturn(cpu: &Cpu, args: ARG_workq_kernreturn) -> (u64, bool) {
    todo!("workq_kernreturn({args:?}): {cpu:#?}");
}

#[inline]
pub fn kevent64(cpu: &Cpu, args: ARG_kevent64) -> (u64, bool) {
    let ARG_kevent64 {
        fd,
        changelist,
        nchanges,
        eventlist,
        nevents,
        flags,
        timeout,
    } = args;
    sys::syscall(
        369,
        [
            fd as u64,
            at!(
                cpu,
                VMA::new(changelist as u64),
                ToSize::to_size(nchanges * 48)
            ),
            nchanges as u64,
            at!(
                cpu,
                VMA::new(eventlist as u64),
                ToSize::to_size(nevents * 48)
            ),
            nevents as u64,
            flags as u64,
            at!(cpu, VMA::new(timeout as u64), ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn ledger(cpu: &Cpu, args: ARG_ledger) -> (u64, bool) {
    todo!("ledger({args:?}): {cpu:#?}");
}

#[inline]
pub fn kevent_qos(cpu: &Cpu, args: ARG_kevent_qos) -> (u64, bool) {
    todo!("kevent_qos({args:?}): {cpu:#?}");
}

#[inline]
pub fn kevent_id(cpu: &Cpu, args: ARG_kevent_id) -> (u64, bool) {
    todo!("kevent_id({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_execve(cpu: &Cpu, args: ARG___mac_execve) -> (u64, bool) {
    todo!("__mac_execve({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_syscall(cpu: &Cpu, args: ARG___mac_syscall) -> (u64, bool) {
    todo!("__mac_syscall({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_get_file(cpu: &Cpu, args: ARG___mac_get_file) -> (u64, bool) {
    todo!("__mac_get_file({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_set_file(cpu: &Cpu, args: ARG___mac_set_file) -> (u64, bool) {
    todo!("__mac_set_file({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_get_link(cpu: &Cpu, args: ARG___mac_get_link) -> (u64, bool) {
    todo!("__mac_get_link({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_set_link(cpu: &Cpu, args: ARG___mac_set_link) -> (u64, bool) {
    todo!("__mac_set_link({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_get_proc(cpu: &Cpu, args: ARG___mac_get_proc) -> (u64, bool) {
    todo!("__mac_get_proc({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_set_proc(cpu: &Cpu, args: ARG___mac_set_proc) -> (u64, bool) {
    todo!("__mac_set_proc({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_get_fd(cpu: &Cpu, args: ARG___mac_get_fd) -> (u64, bool) {
    todo!("__mac_get_fd({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_set_fd(cpu: &Cpu, args: ARG___mac_set_fd) -> (u64, bool) {
    todo!("__mac_set_fd({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_get_pid(cpu: &Cpu, args: ARG___mac_get_pid) -> (u64, bool) {
    todo!("__mac_get_pid({args:?}): {cpu:#?}");
}

#[inline]
pub fn pselect(cpu: &Cpu, args: ARG_pselect) -> (u64, bool) {
    todo!("pselect({args:?}): {cpu:#?}");
}

#[inline]
pub fn pselect_nocancel(cpu: &Cpu, args: ARG_pselect_nocancel) -> (u64, bool) {
    todo!("pselect_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn read_nocancel(cpu: &Cpu, args: ARG_read_nocancel) -> (u64, bool) {
    let ARG_read_nocancel { fd, cbuf, nbyte } = args;
    sys::syscall(
        396,
        [
            fd as u64,
            at!(cpu, cbuf, ToSize::to_size(nbyte)),
            nbyte as u64,
        ],
    )
}

#[inline]
pub fn write_nocancel(cpu: &Cpu, args: ARG_write_nocancel) -> (u64, bool) {
    let ARG_write_nocancel { fd, cbuf, nbyte } = args;
    sys::syscall(
        397,
        [
            fd as u64,
            at!(cpu, cbuf, ToSize::to_size(nbyte)),
            nbyte as u64,
        ],
    )
}

#[inline]
pub fn open_nocancel(cpu: &Cpu, args: ARG_open_nocancel) -> (u64, bool) {
    let ARG_open_nocancel { path, flags, mode } = args;
    sys::syscall(
        398,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn wait4_nocancel(cpu: &Cpu, args: ARG_wait4_nocancel) -> (u64, bool) {
    let ARG_wait4_nocancel {
        pid,
        status,
        options,
        rusage,
    } = args;
    sys::syscall(
        400,
        [
            pid as u64,
            at!(cpu, status, ToSize::to_size(4)),
            options as u64,
            at!(cpu, rusage, ToSize::to_size(144)),
        ],
    )
}

#[inline]
pub fn recvmsg_nocancel(cpu: &Cpu, args: ARG_recvmsg_nocancel) -> (u64, bool) {
    todo!("recvmsg_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn sendmsg_nocancel(cpu: &Cpu, args: ARG_sendmsg_nocancel) -> (u64, bool) {
    todo!("sendmsg_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn recvfrom_nocancel(cpu: &Cpu, args: ARG_recvfrom_nocancel) -> (u64, bool) {
    todo!("recvfrom_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn accept_nocancel(cpu: &Cpu, args: ARG_accept_nocancel) -> (u64, bool) {
    todo!("accept_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn msync_nocancel(cpu: &Cpu, args: ARG_msync_nocancel) -> (u64, bool) {
    todo!("msync_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_fcntl_nocancel(cpu: &Cpu, args: ARG_sys_fcntl_nocancel) -> (u64, bool) {
    todo!("sys_fcntl_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn select_nocancel(cpu: &Cpu, args: ARG_select_nocancel) -> (u64, bool) {
    todo!("select_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn connect_nocancel(cpu: &Cpu, args: ARG_connect_nocancel) -> (u64, bool) {
    let ARG_connect_nocancel { s, name, namelen } = args;
    sys::syscall(
        409,
        [
            s as u64,
            at!(cpu, name, ToSize::to_size(namelen)),
            namelen as u64,
        ],
    )
}

#[inline]
pub fn readv_nocancel(cpu: &Cpu, args: ARG_readv_nocancel) -> (u64, bool) {
    todo!("readv_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn writev_nocancel(cpu: &Cpu, args: ARG_writev_nocancel) -> (u64, bool) {
    todo!("writev_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn sendto_nocancel(cpu: &Cpu, args: ARG_sendto_nocancel) -> (u64, bool) {
    let ARG_sendto_nocancel {
        s,
        buf,
        len,
        flags,
        to,
        tolen,
    } = args;
    sys::syscall(
        413,
        [
            s as u64,
            at!(cpu, buf, ToSize::to_size(len)),
            len as u64,
            flags as u64,
            at!(cpu, to, ToSize::to_size(tolen)),
            tolen as u64,
        ],
    )
}

#[inline]
pub fn pread_nocancel(cpu: &Cpu, args: ARG_pread_nocancel) -> (u64, bool) {
    let ARG_pread_nocancel {
        fd,
        buf,
        nbyte,
        offset,
    } = args;
    sys::syscall(
        414,
        [
            fd as u64,
            at!(cpu, buf, ToSize::to_size(nbyte)),
            nbyte as u64,
            offset as u64,
        ],
    )
}

#[inline]
pub fn pwrite_nocancel(cpu: &Cpu, args: ARG_pwrite_nocancel) -> (u64, bool) {
    let ARG_pwrite_nocancel {
        fd,
        buf,
        nbyte,
        offset,
    } = args;
    sys::syscall(
        415,
        [
            fd as u64,
            at!(cpu, buf, ToSize::to_size(nbyte)),
            nbyte as u64,
            offset as u64,
        ],
    )
}

#[inline]
pub fn waitid_nocancel(cpu: &Cpu, args: ARG_waitid_nocancel) -> (u64, bool) {
    let ARG_waitid_nocancel {
        idtype,
        id,
        infop,
        options,
    } = args;
    sys::syscall(
        416,
        [
            idtype as u64,
            id as u64,
            at!(cpu, VMA::new(infop as u64), ToSize::to_size(104)),
            options as u64,
        ],
    )
}

#[inline]
pub fn poll_nocancel(cpu: &Cpu, args: ARG_poll_nocancel) -> (u64, bool) {
    let ARG_poll_nocancel { fds, nfds, timeout } = args;
    sys::syscall(
        417,
        [
            at!(cpu, VMA::new(fds as u64), ToSize::to_size(nfds * 8)),
            nfds as u64,
            timeout as u64,
        ],
    )
}

#[inline]
pub fn msgsnd_nocancel(cpu: &Cpu, args: ARG_msgsnd_nocancel) -> (u64, bool) {
    let ARG_msgsnd_nocancel {
        msqid,
        msgp,
        msgsz,
        msgflg,
    } = args;
    sys::syscall(
        418,
        [
            msqid as u64,
            at!(cpu, VMA::new(msgp as u64), ToSize::to_size(8 + msgsz)),
            msgsz as u64,
            msgflg as u64,
        ],
    )
}

#[inline]
pub fn msgrcv_nocancel(cpu: &Cpu, args: ARG_msgrcv_nocancel) -> (u64, bool) {
    let ARG_msgrcv_nocancel {
        msqid,
        msgp,
        msgsz,
        msgtyp,
        msgflg,
    } = args;
    sys::syscall(
        419,
        [
            msqid as u64,
            at!(cpu, VMA::new(msgp as u64), ToSize::to_size(8 + msgsz)),
            msgsz as u64,
            msgtyp as u64,
            msgflg as u64,
        ],
    )
}

#[inline]
pub fn sem_wait_nocancel(cpu: &Cpu, args: ARG_sem_wait_nocancel) -> (u64, bool) {
    todo!("sem_wait_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn aio_suspend_nocancel(cpu: &Cpu, args: ARG_aio_suspend_nocancel) -> (u64, bool) {
    let ARG_aio_suspend_nocancel {
        aiocblist,
        nent,
        timeoutp,
    } = args;
    sys::syscall(
        421,
        [
            at!(cpu, aiocblist, ToSize::to_size(nent * 8)),
            nent as u64,
            at!(cpu, timeoutp, ToSize::to_size(16)),
        ],
    )
}

#[inline]
pub fn __sigwait_nocancel(cpu: &Cpu, args: ARG___sigwait_nocancel) -> (u64, bool) {
    let ARG___sigwait_nocancel { set, sig } = args;
    sys::syscall(
        422,
        [
            at!(cpu, set, ToSize::to_size(4)),
            at!(cpu, sig, ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn __mac_mount(cpu: &Cpu, args: ARG___mac_mount) -> (u64, bool) {
    todo!("__mac_mount({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_get_mount(cpu: &Cpu, args: ARG___mac_get_mount) -> (u64, bool) {
    todo!("__mac_get_mount({args:?}): {cpu:#?}");
}

#[inline]
pub fn __mac_getfsstat(cpu: &Cpu, args: ARG___mac_getfsstat) -> (u64, bool) {
    let ARG___mac_getfsstat {
        buf,
        bufsize,
        mac,
        macsize,
        flags,
    } = args;
    sys::syscall(
        426,
        [
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
            at!(cpu, mac, ToSize::to_size(macsize)),
            macsize as u64,
            flags as u64,
        ],
    )
}

#[inline]
pub fn fsgetpath(cpu: &Cpu, args: ARG_fsgetpath) -> (u64, bool) {
    let ARG_fsgetpath {
        buf,
        bufsize,
        fsid,
        objid,
    } = args;
    sys::syscall(
        427,
        [
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
            at!(cpu, fsid, ToSize::to_size(8)),
            objid,
        ],
    )
}

#[inline]
pub fn sys_fileport_makeport(cpu: &Cpu, args: ARG_sys_fileport_makeport) -> (u64, bool) {
    let ARG_sys_fileport_makeport { fd, portnamep } = args;
    sys::syscall(430, [fd as u64, at!(cpu, portnamep, ToSize::to_size(4))])
}

#[inline]
pub fn audit_session_port(cpu: &Cpu, args: ARG_audit_session_port) -> (u64, bool) {
    let ARG_audit_session_port { asid, portnamep } = args;
    sys::syscall(432, [asid as u64, at!(cpu, portnamep, ToSize::to_size(4))])
}

#[inline]
pub fn kas_info(cpu: &Cpu, args: ARG_kas_info) -> (u64, bool) {
    todo!("kas_info({args:?}): {cpu:#?}");
}

#[inline]
pub fn memorystatus_control(cpu: &Cpu, args: ARG_memorystatus_control) -> (u64, bool) {
    todo!("memorystatus_control({args:?}): {cpu:#?}");
}

#[inline]
pub fn guarded_open_np(cpu: &Cpu, args: ARG_guarded_open_np) -> (u64, bool) {
    let ARG_guarded_open_np {
        path,
        guard,
        guardflags,
        flags,
        mode,
    } = args;
    sys::syscall(
        441,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
            guardflags as u64,
            flags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn guarded_close_np(cpu: &Cpu, args: ARG_guarded_close_np) -> (u64, bool) {
    let ARG_guarded_close_np { fd, guard } = args;
    sys::syscall(
        442,
        [
            fd as u64,
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
        ],
    )
}

#[inline]
pub fn guarded_kqueue_np(cpu: &Cpu, args: ARG_guarded_kqueue_np) -> (u64, bool) {
    let ARG_guarded_kqueue_np { guard, guardflags } = args;
    sys::syscall(
        443,
        [
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
            guardflags as u64,
        ],
    )
}

#[inline]
pub fn change_fdguard_np(cpu: &Cpu, args: ARG_change_fdguard_np) -> (u64, bool) {
    let ARG_change_fdguard_np {
        fd,
        guard,
        guardflags,
        nguard,
        nguardflags,
        fdflagsp,
    } = args;
    sys::syscall(
        444,
        [
            fd as u64,
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
            guardflags as u64,
            at!(cpu, VMA::new(nguard as u64), ToSize::to_size(8)),
            nguardflags as u64,
            at!(cpu, VMA::new(fdflagsp as u64), ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn proc_rlimit_control(cpu: &Cpu, args: ARG_proc_rlimit_control) -> (u64, bool) {
    todo!("proc_rlimit_control({args:?}): {cpu:#?}");
}

#[inline]
pub fn connectx(cpu: &Cpu, args: ARG_connectx) -> (u64, bool) {
    todo!("connectx({args:?}): {cpu:#?}");
}

#[inline]
pub fn proc_uuid_policy(cpu: &Cpu, args: ARG_proc_uuid_policy) -> (u64, bool) {
    let ARG_proc_uuid_policy {
        operation,
        uuid,
        uuidlen,
        flags,
    } = args;
    sys::syscall(
        452,
        [
            operation as u64,
            at!(cpu, VMA::new(uuid as u64), ToSize::to_size(uuidlen)),
            uuidlen as u64,
            flags as u64,
        ],
    )
}

#[inline]
pub fn memorystatus_get_level(cpu: &Cpu, args: ARG_memorystatus_get_level) -> (u64, bool) {
    let ARG_memorystatus_get_level { level } = args;
    sys::syscall(453, [at!(cpu, level, ToSize::to_size(4))])
}

#[inline]
pub fn sfi_ctl(cpu: &Cpu, args: ARG_sfi_ctl) -> (u64, bool) {
    let ARG_sfi_ctl {
        operation,
        sfi_class,
        time,
        out_time,
    } = args;
    sys::syscall(
        456,
        [
            operation as u64,
            sfi_class as u64,
            time,
            at!(cpu, VMA::new(out_time as u64), ToSize::to_size(8)),
        ],
    )
}

#[inline]
pub fn sfi_pidctl(cpu: &Cpu, args: ARG_sfi_pidctl) -> (u64, bool) {
    let ARG_sfi_pidctl {
        operation,
        pid,
        sfi_flags,
        out_sfi_flags,
    } = args;
    sys::syscall(
        457,
        [
            operation as u64,
            pid as u64,
            sfi_flags as u64,
            at!(cpu, VMA::new(out_sfi_flags as u64), ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn coalition(cpu: &Cpu, args: ARG_coalition) -> (u64, bool) {
    todo!("coalition({args:?}): {cpu:#?}");
}

#[inline]
pub fn coalition_info(cpu: &Cpu, args: ARG_coalition_info) -> (u64, bool) {
    todo!("coalition_info({args:?}): {cpu:#?}");
}

#[inline]
pub fn necp_match_policy(cpu: &Cpu, args: ARG_necp_match_policy) -> (u64, bool) {
    let ARG_necp_match_policy {
        parameters,
        parameters_size,
        returned_result,
    } = args;
    sys::syscall(
        460,
        [
            at!(
                cpu,
                VMA::new(parameters as u64),
                ToSize::to_size(parameters_size)
            ),
            parameters_size as u64,
            at!(cpu, VMA::new(returned_result as u64), ToSize::to_size(424)),
        ],
    )
}

#[inline]
pub fn getattrlistbulk(cpu: &Cpu, args: ARG_getattrlistbulk) -> (u64, bool) {
    todo!("getattrlistbulk({args:?}): {cpu:#?}");
}

#[inline]
pub fn clonefileat(cpu: &Cpu, args: ARG_clonefileat) -> (u64, bool) {
    let ARG_clonefileat {
        src_dirfd,
        src,
        dst_dirfd,
        dst,
        flags,
    } = args;
    sys::syscall(
        462,
        [
            src_dirfd as u64,
            at!(cpu, src, ToSize::to_size(libc::MAXPATHLEN)),
            dst_dirfd as u64,
            at!(cpu, dst, ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
        ],
    )
}

#[inline]
pub fn openat(cpu: &Cpu, args: ARG_openat) -> (u64, bool) {
    let ARG_openat {
        fd,
        path,
        flags,
        mode,
    } = args;
    sys::syscall(
        463,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn openat_nocancel(cpu: &Cpu, args: ARG_openat_nocancel) -> (u64, bool) {
    let ARG_openat_nocancel {
        fd,
        path,
        flags,
        mode,
    } = args;
    sys::syscall(
        464,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn renameat(cpu: &Cpu, args: ARG_renameat) -> (u64, bool) {
    let ARG_renameat {
        fromfd,
        from,
        tofd,
        to,
    } = args;
    sys::syscall(
        465,
        [
            fromfd as u64,
            at!(
                cpu,
                VMA::new(from as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            tofd as u64,
            at!(cpu, VMA::new(to as u64), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn faccessat(cpu: &Cpu, args: ARG_faccessat) -> (u64, bool) {
    let ARG_faccessat {
        fd,
        path,
        amode,
        flag,
    } = args;
    sys::syscall(
        466,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            amode as u64,
            flag as u64,
        ],
    )
}

#[inline]
pub fn fchmodat(cpu: &Cpu, args: ARG_fchmodat) -> (u64, bool) {
    let ARG_fchmodat {
        fd,
        path,
        mode,
        flag,
    } = args;
    sys::syscall(
        467,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
            flag as u64,
        ],
    )
}

#[inline]
pub fn fchownat(cpu: &Cpu, args: ARG_fchownat) -> (u64, bool) {
    let ARG_fchownat {
        fd,
        path,
        uid,
        gid,
        flag,
    } = args;
    sys::syscall(
        468,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            uid as u64,
            gid as u64,
            flag as u64,
        ],
    )
}

#[inline]
pub fn fstatat(cpu: &Cpu, args: ARG_fstatat) -> (u64, bool) {
    let ARG_fstatat { fd, path, ub, flag } = args;
    sys::syscall(
        469,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, ub, ToSize::to_size(144)),
            flag as u64,
        ],
    )
}

#[inline]
pub fn fstatat64(cpu: &Cpu, args: ARG_fstatat64) -> (u64, bool) {
    let ARG_fstatat64 { fd, path, ub, flag } = args;
    sys::syscall(
        470,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, ub, ToSize::to_size(144)),
            flag as u64,
        ],
    )
}

#[inline]
pub fn linkat(cpu: &Cpu, args: ARG_linkat) -> (u64, bool) {
    let ARG_linkat {
        fd1,
        path,
        fd2,
        link,
        flag,
    } = args;
    sys::syscall(
        471,
        [
            fd1 as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            fd2 as u64,
            at!(cpu, link, ToSize::to_size(libc::MAXPATHLEN)),
            flag as u64,
        ],
    )
}

#[inline]
pub fn unlinkat(cpu: &Cpu, args: ARG_unlinkat) -> (u64, bool) {
    let ARG_unlinkat { fd, path, flag } = args;
    sys::syscall(
        472,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flag as u64,
        ],
    )
}

#[inline]
pub fn readlinkat(cpu: &Cpu, args: ARG_readlinkat) -> (u64, bool) {
    let ARG_readlinkat {
        fd,
        path,
        buf,
        bufsize,
    } = args;
    sys::syscall(
        473,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
        ],
    )
}

#[inline]
pub fn symlinkat(cpu: &Cpu, args: ARG_symlinkat) -> (u64, bool) {
    let ARG_symlinkat { path1, fd, path2 } = args;
    sys::syscall(
        474,
        [
            at!(
                cpu,
                VMA::new(path1 as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            fd as u64,
            at!(cpu, path2.vma(), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn mkdirat(cpu: &Cpu, args: ARG_mkdirat) -> (u64, bool) {
    let ARG_mkdirat { fd, path, mode } = args;
    sys::syscall(
        475,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
        ],
    )
}

#[inline]
pub fn getattrlistat(cpu: &Cpu, args: ARG_getattrlistat) -> (u64, bool) {
    todo!("getattrlistat({args:?}): {cpu:#?}");
}

#[inline]
pub fn bsdthread_ctl(cpu: &Cpu, args: ARG_bsdthread_ctl) -> (u64, bool) {
    todo!("bsdthread_ctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn openbyid_np(cpu: &Cpu, args: ARG_openbyid_np) -> (u64, bool) {
    let ARG_openbyid_np {
        fsid,
        objid,
        oflags,
    } = args;
    sys::syscall(
        479,
        [
            at!(cpu, fsid, ToSize::to_size(8)),
            at!(cpu, objid, ToSize::to_size(8)),
            oflags as u64,
        ],
    )
}

#[inline]
pub fn recvmsg_x(cpu: &Cpu, args: ARG_recvmsg_x) -> (u64, bool) {
    todo!("recvmsg_x({args:?}): {cpu:#?}");
}

#[inline]
pub fn sendmsg_x(cpu: &Cpu, args: ARG_sendmsg_x) -> (u64, bool) {
    todo!("sendmsg_x({args:?}): {cpu:#?}");
}

#[inline]
pub fn csrctl(cpu: &Cpu, args: ARG_csrctl) -> (u64, bool) {
    todo!("csrctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn guarded_open_dprotected_np(cpu: &Cpu, args: ARG_guarded_open_dprotected_np) -> (u64, bool) {
    let ARG_guarded_open_dprotected_np {
        path,
        guard,
        guardflags,
        flags,
        dpclass,
        dpflags,
        mode,
    } = args;
    sys::syscall(
        484,
        [
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
            guardflags as u64,
            flags as u64,
            dpclass as u64,
            dpflags as u64,
            mode as u64,
        ],
    )
}

#[inline]
pub fn guarded_write_np(cpu: &Cpu, args: ARG_guarded_write_np) -> (u64, bool) {
    let ARG_guarded_write_np {
        fd,
        guard,
        cbuf,
        nbyte,
    } = args;
    sys::syscall(
        485,
        [
            fd as u64,
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
            at!(cpu, cbuf, ToSize::to_size(nbyte)),
            nbyte as u64,
        ],
    )
}

#[inline]
pub fn guarded_pwrite_np(cpu: &Cpu, args: ARG_guarded_pwrite_np) -> (u64, bool) {
    let ARG_guarded_pwrite_np {
        fd,
        guard,
        buf,
        nbyte,
        offset,
    } = args;
    sys::syscall(
        486,
        [
            fd as u64,
            at!(cpu, VMA::new(guard as u64), ToSize::to_size(8)),
            at!(cpu, buf, ToSize::to_size(nbyte)),
            nbyte as u64,
            offset as u64,
        ],
    )
}

#[inline]
pub fn guarded_writev_np(cpu: &Cpu, args: ARG_guarded_writev_np) -> (u64, bool) {
    todo!("guarded_writev_np({args:?}): {cpu:#?}");
}

#[inline]
pub fn renameatx_np(cpu: &Cpu, args: ARG_renameatx_np) -> (u64, bool) {
    let ARG_renameatx_np {
        fromfd,
        from,
        tofd,
        to,
        flags,
    } = args;
    sys::syscall(
        488,
        [
            fromfd as u64,
            at!(
                cpu,
                VMA::new(from as u64),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            tofd as u64,
            at!(cpu, VMA::new(to as u64), ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
        ],
    )
}

#[inline]
pub fn mremap_encrypted(cpu: &Cpu, args: ARG_mremap_encrypted) -> (u64, bool) {
    todo!("mremap_encrypted({args:?}): {cpu:#?}");
}

#[inline]
pub fn netagent_trigger(cpu: &Cpu, args: ARG_netagent_trigger) -> (u64, bool) {
    let ARG_netagent_trigger {
        agent_uuid,
        agent_uuidlen,
    } = args;
    sys::syscall(
        490,
        [
            at!(
                cpu,
                VMA::new(agent_uuid as u64),
                ToSize::to_size(agent_uuidlen)
            ),
            agent_uuidlen as u64,
        ],
    )
}

#[inline]
pub fn stack_snapshot_with_config(cpu: &Cpu, args: ARG_stack_snapshot_with_config) -> (u64, bool) {
    let ARG_stack_snapshot_with_config {
        stackshot_config_version,
        stackshot_config,
        stackshot_config_size,
    } = args;
    sys::syscall(
        491,
        [
            stackshot_config_version as u64,
            at!(
                cpu,
                stackshot_config,
                ToSize::to_size(stackshot_config_size)
            ),
            stackshot_config_size as u64,
        ],
    )
}

#[inline]
pub fn microstackshot(cpu: &Cpu, args: ARG_microstackshot) -> (u64, bool) {
    let ARG_microstackshot {
        tracebuf,
        tracebuf_size,
        flags,
    } = args;
    sys::syscall(
        492,
        [
            at!(cpu, tracebuf, ToSize::to_size(tracebuf_size)),
            tracebuf_size as u64,
            flags as u64,
        ],
    )
}

#[inline]
pub fn grab_pgo_data(cpu: &Cpu, args: ARG_grab_pgo_data) -> (u64, bool) {
    let ARG_grab_pgo_data {
        uuid,
        flags,
        buffer,
        size,
    } = args;
    sys::syscall(
        493,
        [
            at!(cpu, uuid, ToSize::to_size(16)),
            flags as u64,
            at!(cpu, buffer, ToSize::to_size(size)),
            size as u64,
        ],
    )
}

#[inline]
pub fn persona(cpu: &Cpu, args: ARG_persona) -> (u64, bool) {
    todo!("persona({args:?}): {cpu:#?}");
}

#[inline]
pub fn work_interval_ctl(cpu: &Cpu, args: ARG_work_interval_ctl) -> (u64, bool) {
    todo!("work_interval_ctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn getentropy(cpu: &Cpu, args: ARG_getentropy) -> (u64, bool) {
    let ARG_getentropy { buffer, size } = args;
    sys::syscall(
        500,
        [
            at!(cpu, VMA::new(buffer as u64), ToSize::to_size(size)),
            size as u64,
        ],
    )
}

#[inline]
pub fn necp_client_action(cpu: &Cpu, args: ARG_necp_client_action) -> (u64, bool) {
    todo!("necp_client_action({args:?}): {cpu:#?}");
}

#[inline]
pub fn __nexus_open(cpu: &Cpu, args: ARG___nexus_open) -> (u64, bool) {
    let ARG___nexus_open { init, init_len } = args;
    sys::syscall(
        503,
        [
            at!(cpu, VMA::new(init as u64), ToSize::to_size(init_len)),
            init_len as u64,
        ],
    )
}

#[inline]
pub fn __nexus_register(cpu: &Cpu, args: ARG___nexus_register) -> (u64, bool) {
    let ARG___nexus_register {
        ctl,
        reg,
        reg_len,
        prov_uuid,
        prov_uuid_len,
    } = args;
    sys::syscall(
        504,
        [
            ctl as u64,
            at!(cpu, VMA::new(reg as u64), ToSize::to_size(reg_len)),
            reg_len as u64,
            at!(
                cpu,
                VMA::new(prov_uuid as u64),
                ToSize::to_size(prov_uuid_len)
            ),
            prov_uuid_len as u64,
        ],
    )
}

#[inline]
pub fn __nexus_deregister(cpu: &Cpu, args: ARG___nexus_deregister) -> (u64, bool) {
    let ARG___nexus_deregister {
        ctl,
        prov_uuid,
        prov_uuid_len,
    } = args;
    sys::syscall(
        505,
        [
            ctl as u64,
            at!(
                cpu,
                VMA::new(prov_uuid as u64),
                ToSize::to_size(prov_uuid_len)
            ),
            prov_uuid_len as u64,
        ],
    )
}

#[inline]
pub fn __nexus_create(cpu: &Cpu, args: ARG___nexus_create) -> (u64, bool) {
    let ARG___nexus_create {
        ctl,
        prov_uuid,
        prov_uuid_len,
        nx_uuid,
        nx_uuid_len,
    } = args;
    sys::syscall(
        506,
        [
            ctl as u64,
            at!(
                cpu,
                VMA::new(prov_uuid as u64),
                ToSize::to_size(prov_uuid_len)
            ),
            prov_uuid_len as u64,
            at!(cpu, VMA::new(nx_uuid as u64), ToSize::to_size(nx_uuid_len)),
            nx_uuid_len as u64,
        ],
    )
}

#[inline]
pub fn __nexus_destroy(cpu: &Cpu, args: ARG___nexus_destroy) -> (u64, bool) {
    let ARG___nexus_destroy {
        ctl,
        nx_uuid,
        nx_uuid_len,
    } = args;
    sys::syscall(
        507,
        [
            ctl as u64,
            at!(cpu, VMA::new(nx_uuid as u64), ToSize::to_size(nx_uuid_len)),
            nx_uuid_len as u64,
        ],
    )
}

#[inline]
pub fn __nexus_get_opt(cpu: &Cpu, args: ARG___nexus_get_opt) -> (u64, bool) {
    todo!("__nexus_get_opt({args:?}): {cpu:#?}");
}

#[inline]
pub fn __nexus_set_opt(cpu: &Cpu, args: ARG___nexus_set_opt) -> (u64, bool) {
    let ARG___nexus_set_opt {
        ctl,
        opt,
        aoptval,
        optlen,
    } = args;
    sys::syscall(
        509,
        [
            ctl as u64,
            opt as u64,
            at!(cpu, VMA::new(aoptval as u64), ToSize::to_size(optlen)),
            optlen as u64,
        ],
    )
}

#[inline]
pub fn __channel_open(cpu: &Cpu, args: ARG___channel_open) -> (u64, bool) {
    let ARG___channel_open { init, init_len } = args;
    sys::syscall(
        510,
        [
            at!(cpu, VMA::new(init as u64), ToSize::to_size(init_len)),
            init_len as u64,
        ],
    )
}

#[inline]
pub fn __channel_get_info(cpu: &Cpu, args: ARG___channel_get_info) -> (u64, bool) {
    let ARG___channel_get_info { c, cinfo, cinfolen } = args;
    sys::syscall(
        511,
        [
            c as u64,
            at!(cpu, VMA::new(cinfo as u64), ToSize::to_size(cinfolen)),
            cinfolen as u64,
        ],
    )
}

#[inline]
pub fn __channel_get_opt(cpu: &Cpu, args: ARG___channel_get_opt) -> (u64, bool) {
    todo!("__channel_get_opt({args:?}): {cpu:#?}");
}

#[inline]
pub fn __channel_set_opt(cpu: &Cpu, args: ARG___channel_set_opt) -> (u64, bool) {
    let ARG___channel_set_opt {
        c,
        opt,
        aoptval,
        optlen,
    } = args;
    sys::syscall(
        514,
        [
            c as u64,
            opt as u64,
            at!(cpu, VMA::new(aoptval as u64), ToSize::to_size(optlen)),
            optlen as u64,
        ],
    )
}

#[inline]
pub fn sys_ulock_wait(cpu: &Cpu, args: ARG_sys_ulock_wait) -> (u64, bool) {
    todo!("sys_ulock_wait({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_ulock_wake(cpu: &Cpu, args: ARG_sys_ulock_wake) -> (u64, bool) {
    todo!("sys_ulock_wake({args:?}): {cpu:#?}");
}

#[inline]
pub fn fclonefileat(cpu: &Cpu, args: ARG_fclonefileat) -> (u64, bool) {
    let ARG_fclonefileat {
        src_fd,
        dst_dirfd,
        dst,
        flags,
    } = args;
    sys::syscall(
        517,
        [
            src_fd as u64,
            dst_dirfd as u64,
            at!(cpu, dst, ToSize::to_size(libc::MAXPATHLEN)),
            flags as u64,
        ],
    )
}

#[inline]
pub fn fs_snapshot(cpu: &Cpu, args: ARG_fs_snapshot) -> (u64, bool) {
    todo!("fs_snapshot({args:?}): {cpu:#?}");
}

#[inline]
pub fn terminate_with_payload(cpu: &Cpu, args: ARG_terminate_with_payload) -> (u64, bool) {
    let ARG_terminate_with_payload {
        pid,
        reason_namespace,
        reason_code,
        payload,
        payload_size,
        reason_string,
        reason_flags,
    } = args;
    sys::syscall(
        520,
        [
            pid as u64,
            reason_namespace as u64,
            reason_code,
            at!(cpu, VMA::new(payload as u64), ToSize::to_size(payload_size)),
            payload_size as u64,
            at!(cpu, reason_string.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            reason_flags,
        ],
    )
}

#[inline]
pub fn abort_with_payload(cpu: &Cpu, args: ARG_abort_with_payload) -> (u64, bool) {
    let ARG_abort_with_payload {
        reason_namespace,
        reason_code,
        payload,
        payload_size,
        reason_string,
        reason_flags,
    } = args;
    sys::syscall(
        521,
        [
            reason_namespace as u64,
            reason_code,
            at!(cpu, VMA::new(payload as u64), ToSize::to_size(payload_size)),
            payload_size as u64,
            at!(cpu, reason_string.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            reason_flags,
        ],
    )
}

#[inline]
pub fn necp_session_action(cpu: &Cpu, args: ARG_necp_session_action) -> (u64, bool) {
    todo!("necp_session_action({args:?}): {cpu:#?}");
}

#[inline]
pub fn setattrlistat(cpu: &Cpu, args: ARG_setattrlistat) -> (u64, bool) {
    todo!("setattrlistat({args:?}): {cpu:#?}");
}

#[inline]
pub fn net_qos_guideline(cpu: &Cpu, args: ARG_net_qos_guideline) -> (u64, bool) {
    let ARG_net_qos_guideline { param, param_len } = args;
    sys::syscall(
        525,
        [
            at!(cpu, VMA::new(param as u64), ToSize::to_size(param_len)),
            param_len as u64,
        ],
    )
}

#[inline]
pub fn fmount(cpu: &Cpu, args: ARG_fmount) -> (u64, bool) {
    todo!("fmount({args:?}): {cpu:#?}");
}

#[inline]
pub fn ntp_adjtime(cpu: &Cpu, args: ARG_ntp_adjtime) -> (u64, bool) {
    let ARG_ntp_adjtime { tp } = args;
    sys::syscall(527, [at!(cpu, VMA::new(tp as u64), ToSize::to_size(208))])
}

#[inline]
pub fn ntp_gettime(cpu: &Cpu, args: ARG_ntp_gettime) -> (u64, bool) {
    let ARG_ntp_gettime { ntvp } = args;
    sys::syscall(528, [at!(cpu, VMA::new(ntvp as u64), ToSize::to_size(24))])
}

#[inline]
pub fn os_fault_with_payload(cpu: &Cpu, args: ARG_os_fault_with_payload) -> (u64, bool) {
    let ARG_os_fault_with_payload {
        reason_namespace,
        reason_code,
        payload,
        payload_size,
        reason_string,
        reason_flags,
    } = args;
    sys::syscall(
        529,
        [
            reason_namespace as u64,
            reason_code,
            at!(cpu, VMA::new(payload as u64), ToSize::to_size(payload_size)),
            payload_size as u64,
            at!(cpu, reason_string.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            reason_flags,
        ],
    )
}

#[inline]
pub fn kqueue_workloop_ctl(cpu: &Cpu, args: ARG_kqueue_workloop_ctl) -> (u64, bool) {
    todo!("kqueue_workloop_ctl({args:?}): {cpu:#?}");
}

#[inline]
pub fn coalition_ledger(cpu: &Cpu, args: ARG_coalition_ledger) -> (u64, bool) {
    todo!("coalition_ledger({args:?}): {cpu:#?}");
}

#[inline]
pub fn log_data(cpu: &Cpu, args: ARG_log_data) -> (u64, bool) {
    let ARG_log_data {
        tag,
        flags,
        buffer,
        size,
    } = args;
    sys::syscall(
        533,
        [
            tag as u64,
            flags as u64,
            at!(cpu, VMA::new(buffer as u64), ToSize::to_size(size)),
            size as u64,
        ],
    )
}

#[inline]
pub fn shared_region_map_and_slide_2_np(
    cpu: &Cpu,
    args: ARG_shared_region_map_and_slide_2_np,
) -> (u64, bool) {
    let ARG_shared_region_map_and_slide_2_np {
        files_count,
        files,
        mappings_count,
        mappings_u,
    } = args;
    sys::syscall(
        536,
        [
            files_count as u64,
            at!(
                cpu,
                VMA::new(files as u64),
                ToSize::to_size(files_count * 72)
            ),
            mappings_count as u64,
            at!(
                cpu,
                VMA::new(mappings_u as u64),
                ToSize::to_size(mappings_count * 32)
            ),
        ],
    )
}

#[inline]
pub fn pivot_root(cpu: &Cpu, args: ARG_pivot_root) -> (u64, bool) {
    let ARG_pivot_root {
        new_rootfs_path_before,
        old_rootfs_path_after,
    } = args;
    sys::syscall(
        537,
        [
            at!(
                cpu,
                new_rootfs_path_before.vma(),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
            at!(
                cpu,
                old_rootfs_path_after.vma(),
                ToSize::to_size(libc::MAXPATHLEN)
            ),
        ],
    )
}

#[inline]
pub fn task_inspect_for_pid(cpu: &Cpu, args: ARG_task_inspect_for_pid) -> (u64, bool) {
    let ARG_task_inspect_for_pid {
        target_tport,
        pid,
        t,
    } = args;
    sys::syscall(
        538,
        [
            target_tport as u64,
            pid as u64,
            at!(cpu, VMA::new(t as u64), ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn task_read_for_pid(cpu: &Cpu, args: ARG_task_read_for_pid) -> (u64, bool) {
    let ARG_task_read_for_pid {
        target_tport,
        pid,
        t,
    } = args;
    sys::syscall(
        539,
        [
            target_tport as u64,
            pid as u64,
            at!(cpu, VMA::new(t as u64), ToSize::to_size(4)),
        ],
    )
}

#[inline]
pub fn sys_preadv(cpu: &Cpu, args: ARG_sys_preadv) -> (u64, bool) {
    todo!("sys_preadv({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_pwritev(cpu: &Cpu, args: ARG_sys_pwritev) -> (u64, bool) {
    todo!("sys_pwritev({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_preadv_nocancel(cpu: &Cpu, args: ARG_sys_preadv_nocancel) -> (u64, bool) {
    todo!("sys_preadv_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_pwritev_nocancel(cpu: &Cpu, args: ARG_sys_pwritev_nocancel) -> (u64, bool) {
    todo!("sys_pwritev_nocancel({args:?}): {cpu:#?}");
}

#[inline]
pub fn sys_ulock_wait2(cpu: &Cpu, args: ARG_sys_ulock_wait2) -> (u64, bool) {
    todo!("sys_ulock_wait2({args:?}): {cpu:#?}");
}

#[inline]
pub fn proc_info_extended_id(cpu: &Cpu, args: ARG_proc_info_extended_id) -> (u64, bool) {
    todo!("proc_info_extended_id({args:?}): {cpu:#?}");
}

#[inline]
pub fn tracker_action(cpu: &Cpu, args: ARG_tracker_action) -> (u64, bool) {
    todo!("tracker_action({args:?}): {cpu:#?}");
}

#[inline]
pub fn graftdmg(cpu: &Cpu, args: ARG_graftdmg) -> (u64, bool) {
    let ARG_graftdmg {
        dmg_fd,
        mountdir,
        graft_type,
        gda,
    } = args;
    sys::syscall(
        549,
        [
            dmg_fd as u64,
            at!(cpu, mountdir.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            graft_type as u64,
            at!(cpu, VMA::new(gda as u64), ToSize::to_size(512)),
        ],
    )
}

#[inline]
pub fn map_with_linking_np(cpu: &Cpu, args: ARG_map_with_linking_np) -> (u64, bool) {
    let ARG_map_with_linking_np {
        regions,
        region_count,
        link_info,
        link_info_size,
    } = args;
    sys::syscall(
        550,
        [
            at!(
                cpu,
                VMA::new(regions as u64),
                ToSize::to_size(region_count * 32)
            ),
            region_count as u64,
            at!(
                cpu,
                VMA::new(link_info as u64),
                ToSize::to_size(link_info_size)
            ),
            link_info_size as u64,
        ],
    )
}

#[inline]
pub fn freadlink(cpu: &Cpu, args: ARG_freadlink) -> (u64, bool) {
    let ARG_freadlink { fd, buf, bufsize } = args;
    sys::syscall(
        551,
        [
            fd as u64,
            at!(cpu, buf, ToSize::to_size(bufsize)),
            bufsize as u64,
        ],
    )
}

#[inline]
pub fn sys_record_system_event(cpu: &Cpu, args: ARG_sys_record_system_event) -> (u64, bool) {
    let ARG_sys_record_system_event {
        r#type,
        subsystem,
        event,
        payload,
    } = args;
    sys::syscall(
        552,
        [
            r#type as u64,
            subsystem as u64,
            at!(cpu, event.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            at!(cpu, payload.vma(), ToSize::to_size(libc::MAXPATHLEN)),
        ],
    )
}

#[inline]
pub fn mkfifoat(cpu: &Cpu, args: ARG_mkfifoat) -> (u64, bool) {
    let ARG_mkfifoat { fd, path, mode } = args;
    sys::syscall(
        553,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
        ],
    )
}

#[inline]
pub fn mknodat(cpu: &Cpu, args: ARG_mknodat) -> (u64, bool) {
    let ARG_mknodat {
        fd,
        path,
        mode,
        dev,
    } = args;
    sys::syscall(
        554,
        [
            fd as u64,
            at!(cpu, path.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            mode as u64,
            dev as u64,
        ],
    )
}

#[inline]
pub fn ungraftdmg(cpu: &Cpu, args: ARG_ungraftdmg) -> (u64, bool) {
    let ARG_ungraftdmg { mountdir, flags } = args;
    sys::syscall(
        555,
        [
            at!(cpu, mountdir.vma(), ToSize::to_size(libc::MAXPATHLEN)),
            flags,
        ],
    )
}
