[package]
edition = "2024"
name    = "tinyvm"
version = "0.1.0"

[dependencies]
bitflags           = "2.11"
bytes              = "1.11"
libc               = "0.2"
paste              = "1.0"
tracing            = "0.1"
tracing-core       = "0.1"
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }

[build-dependencies]
bindgen = "0.72"
