//! Generated by `genmachtraps.py`, DO NOT EDIT.

use crate::aarch64::{cpu::Cpu, syscall::mach::*};

#[inline]
pub fn _kernelrpc_mach_vm_allocate_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_vm_allocate_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_vm_purgable_control_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_vm_purgable_control_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_vm_deallocate_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_vm_deallocate_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn task_dyld_process_info_notify_get_trap(
    _cpu: &Cpu,
    _args: ARG_task_dyld_process_info_notify_get_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_vm_protect_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_vm_protect_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_vm_map_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_vm_map_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_port_allocate_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_port_allocate_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_port_construct_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_port_construct_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn task_self_trap(_cpu: &Cpu) -> mach2::port::mach_port_name_t {
    unsafe { mach2::traps::mach_task_self() }
}

#[inline]
pub fn mach_msg_trap(_cpu: &Cpu, _args: ARG_mach_msg_trap) -> mach2::message::mach_msg_return_t {
    mach2::kern_return::KERN_NOT_SUPPORTED
}

#[inline]
pub fn mach_msg_overwrite_trap(
    _cpu: &Cpu,
    _args: ARG_mach_msg_overwrite_trap,
) -> mach2::message::mach_msg_return_t {
    mach2::kern_return::KERN_NOT_SUPPORTED
}

#[inline]
pub fn _kernelrpc_mach_port_get_attributes_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_port_get_attributes_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn mach_generate_activity_id(
    _cpu: &Cpu,
    _args: ARG_mach_generate_activity_id,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn task_name_for_pid(
    _cpu: &Cpu,
    _args: ARG_task_name_for_pid,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn task_for_pid(_cpu: &Cpu, _args: ARG_task_for_pid) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn pid_for_task(_cpu: &Cpu, _args: ARG_pid_for_task) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn mach_msg2_trap(_cpu: &Cpu, _args: ARG_mach_msg2_trap) -> mach2::message::mach_msg_return_t {
    todo!();
}

#[inline]
pub fn clock_sleep_trap(
    _cpu: &Cpu,
    _args: ARG_clock_sleep_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn mach_vm_reclaim_update_kernel_accounting_trap(
    _cpu: &Cpu,
    _args: ARG_mach_vm_reclaim_update_kernel_accounting_trap,
) -> mach2::error::mach_error_t {
    todo!();
}

#[inline]
pub fn host_create_mach_voucher_trap(
    _cpu: &Cpu,
    _args: ARG_host_create_mach_voucher_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn mach_voucher_extract_attr_recipe_trap(
    _cpu: &Cpu,
    _args: ARG_mach_voucher_extract_attr_recipe_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_port_type_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_port_type_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn _kernelrpc_mach_port_request_notification_trap(
    _cpu: &Cpu,
    _args: ARG__kernelrpc_mach_port_request_notification_trap,
) -> mach2::kern_return::kern_return_t {
    todo!();
}

#[inline]
pub fn debug_control_port_for_pid(
    _cpu: &Cpu,
    _args: ARG_debug_control_port_for_pid,
) -> mach2::kern_return::kern_return_t {
    todo!();
}
