//! Generated by `genmachtraps.py`, DO NOT EDIT.

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use std::fmt::{Debug, Formatter, Result as FmtResult};

use crate::utils::ptr::Uintptr;

pub type mach_msg_priority_t = u32;
pub type mach_port_flavor_t = i32;
pub type mach_port_info_t = *mut i32;
pub type mach_port_name_array_t = *mut mach2::port::mach_port_name_t;

pub const MACH_MSG_OPTION_NONE: u64 = 0x00000000;
pub const MACH_SEND_MSG: u64 = 0x00000001;
pub const MACH_RCV_MSG: u64 = 0x00000002;
pub const MACH_RCV_LARGE: u64 = 0x00000004;
pub const MACH_RCV_LARGE_IDENTITY: u64 = 0x00000008;
pub const MACH_SEND_TIMEOUT: u64 = 0x00000010;
pub const MACH_SEND_OVERRIDE: u64 = 0x00000020;
pub const MACH_SEND_INTERRUPT: u64 = 0x00000040;
pub const MACH_SEND_NOTIFY: u64 = 0x00000080;
pub const MACH_SEND_ALWAYS: u64 = 0x00010000;
pub const MACH_SEND_FILTER_NONFATAL: u64 = 0x00010000;
pub const MACH_SEND_TRAILER: u64 = 0x00020000;
pub const MACH_SEND_NOIMPORTANCE: u64 = 0x00040000;
pub const MACH_SEND_NODENAP: u64 = MACH_SEND_NOIMPORTANCE;
pub const MACH_SEND_IMPORTANCE: u64 = 0x00080000;
pub const MACH_SEND_SYNC_OVERRIDE: u64 = 0x00100000;
pub const MACH_SEND_PROPAGATE_QOS: u64 = 0x00200000;
pub const MACH_SEND_SYNC_USE_THRPRI: u64 = MACH_SEND_PROPAGATE_QOS;
pub const MACH_SEND_KERNEL: u64 = 0x00400000;
pub const MACH_SEND_SYNC_BOOTSTRAP_CHECKIN: u64 = 0x00800000;
pub const MACH_RCV_TIMEOUT: u64 = 0x00000100;
pub const MACH_RCV_NOTIFY: u64 = 0x00000000;
pub const MACH_RCV_INTERRUPT: u64 = 0x00000400;
pub const MACH_RCV_VOUCHER: u64 = 0x00000800;
pub const MACH_RCV_OVERWRITE: u64 = 0x00000000;
pub const MACH_RCV_GUARDED_DESC: u64 = 0x00001000;
pub const MACH_RCV_SYNC_WAIT: u64 = 0x00004000;
pub const MACH_RCV_SYNC_PEEK: u64 = 0x00008000;
pub const MACH_MSG_STRICT_REPLY: u64 = 0x00000200;

bitflags::bitflags! {
    #[repr(C)]
    #[derive(Debug, Clone, Copy)]
    pub struct mach_msg_option64_t : u64 {
        const MACH64_MSG_OPTION_NONE             = 0;
        const MACH64_SEND_MSG                    = MACH_SEND_MSG;
        const MACH64_RCV_MSG                     = MACH_RCV_MSG;
        const MACH64_RCV_LARGE                   = MACH_RCV_LARGE;
        const MACH64_RCV_LARGE_IDENTITY          = MACH_RCV_LARGE_IDENTITY;
        const MACH64_SEND_TIMEOUT                = MACH_SEND_TIMEOUT;
        const MACH64_SEND_OVERRIDE               = MACH_SEND_OVERRIDE;
        const MACH64_SEND_INTERRUPT              = MACH_SEND_INTERRUPT;
        const MACH64_SEND_NOTIFY                 = MACH_SEND_NOTIFY;
        const MACH64_SEND_ALWAYS                 = MACH_SEND_ALWAYS;
        const MACH64_SEND_IMPORTANCE             = MACH_SEND_IMPORTANCE;
        const MACH64_SEND_KERNEL                 = MACH_SEND_KERNEL;
        const MACH64_SEND_FILTER_NONFATAL        = MACH_SEND_FILTER_NONFATAL;
        const MACH64_SEND_TRAILER                = MACH_SEND_TRAILER;
        const MACH64_SEND_NOIMPORTANCE           = MACH_SEND_NOIMPORTANCE;
        const MACH64_SEND_NODENAP                = MACH_SEND_NODENAP;
        const MACH64_SEND_SYNC_OVERRIDE          = MACH_SEND_SYNC_OVERRIDE;
        const MACH64_SEND_PROPAGATE_QOS          = MACH_SEND_PROPAGATE_QOS;
        const MACH64_SEND_SYNC_BOOTSTRAP_CHECKIN = MACH_SEND_SYNC_BOOTSTRAP_CHECKIN;
        const MACH64_RCV_TIMEOUT                 = MACH_RCV_TIMEOUT;
        const MACH64_RCV_INTERRUPT               = MACH_RCV_INTERRUPT;
        const MACH64_RCV_VOUCHER                 = MACH_RCV_VOUCHER;
        const MACH64_RCV_GUARDED_DESC            = MACH_RCV_GUARDED_DESC;
        const MACH64_RCV_SYNC_WAIT               = MACH_RCV_SYNC_WAIT;
        const MACH64_RCV_SYNC_PEEK               = MACH_RCV_SYNC_PEEK;
        const MACH64_MSG_STRICT_REPLY            = MACH_MSG_STRICT_REPLY;
        const MACH64_MSG_VECTOR                  = 0x0000000100000000;
        const MACH64_SEND_KOBJECT_CALL           = 0x0000000200000000;
        const MACH64_SEND_MQ_CALL                = 0x0000000400000000;
        const MACH64_SEND_ANY                    = 0x0000000800000000;
        const MACH64_SEND_DK_CALL                = 0x0000001000000000;
        const MACH64_POLICY_KERNEL_EXTENSION     = 0x0000002000000000;
        const MACH64_POLICY_FILTER_NON_FATAL     = 0x0000004000000000;
        const MACH64_POLICY_FILTER_MSG           = 0x0000008000000000;
        const MACH64_POLICY_DEFAULT              = 0x0000010000000000;
        const MACH64_POLICY_ENHANCED             = 0x0000020000000000;
        const MACH64_POLICY_PLATFORM             = 0x0000040000000000;
        const MACH64_POLICY_KERNEL               = 0x0000100000000000;
        const MACH64_POLICY_SIMULATED            = 0x0000200000000000;
        const MACH64_POLICY_TRANSLATED           = 0x0000400000000000;
        const MACH64_POLICY_OPTED_OUT            = 0x0000800000000000;
        const MACH64_POLICY_ENHANCED_V0          = 0x0001000000000000;
        const MACH64_POLICY_ENHANCED_V1          = 0x0002000000000000;
        const MACH64_POLICY_ENHANCED_V2          = 0x0004000000000000;
        const MACH64_RCV_LINEAR_VECTOR           = 0x1000000000000000;
        const MACH64_RCV_STACK                   = 0x2000000000000000;
        const MACH64_MACH_MSG2                   = 0x8000000000000000;
    }
}

impl mach_msg_option64_t {
    pub const MACH64_POLICY_ENHANCED_VERSION_MASK: Self = {
        Self::MACH64_POLICY_ENHANCED_V0
            .union(Self::MACH64_POLICY_ENHANCED_V1)
            .union(Self::MACH64_POLICY_ENHANCED_V2)
    };

    pub const MACH64_POLICY_MASK: Self = {
        Self::MACH64_POLICY_DEFAULT
            .union(Self::MACH64_POLICY_ENHANCED)
            .union(Self::MACH64_POLICY_PLATFORM)
            .union(Self::MACH64_POLICY_KERNEL)
            .union(Self::MACH64_POLICY_SIMULATED)
            .union(Self::MACH64_POLICY_TRANSLATED)
            .union(Self::MACH64_POLICY_OPTED_OUT)
    };
}

trait Arg {
    fn decode(args: &[u64; 9]) -> Self;
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_vm_allocate_trap {
    pub target: mach2::port::mach_port_name_t,
    pub addr: *mut mach2::vm_types::mach_vm_offset_t,
    pub size: mach2::vm_types::mach_vm_size_t,
    pub flags: i32,
}

impl Arg for ARG__kernelrpc_mach_vm_allocate_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            addr: args[1] as *mut mach2::vm_types::mach_vm_offset_t,
            size: args[2] as mach2::vm_types::mach_vm_size_t,
            flags: args[3] as i32,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_vm_allocate_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, addr={:?}, size={:?}, flags={:?}",
            self.target, self.addr, self.size, self.flags
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_vm_purgable_control_trap {
    pub target: mach2::port::mach_port_name_t,
    pub address: mach2::vm_types::mach_vm_offset_t,
    pub control: mach2::vm_purgable::vm_purgable_t,
    pub state: *mut i32,
}

impl Arg for ARG__kernelrpc_mach_vm_purgable_control_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            address: args[1] as mach2::vm_types::mach_vm_offset_t,
            control: args[2] as mach2::vm_purgable::vm_purgable_t,
            state: args[3] as *mut i32,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_vm_purgable_control_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, address={:?}, control={:?}, state={:?}",
            self.target, self.address, self.control, self.state
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_vm_deallocate_trap {
    pub target: mach2::port::mach_port_name_t,
    pub address: Uintptr,
    pub size: mach2::vm_types::mach_vm_size_t,
}

impl Arg for ARG__kernelrpc_mach_vm_deallocate_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            address: Uintptr::from(args[1]),
            size: args[2] as mach2::vm_types::mach_vm_size_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_vm_deallocate_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, address={:?}, size={:?}",
            self.target, self.address, self.size
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_task_dyld_process_info_notify_get_trap {
    pub names_addr: mach_port_name_array_t,
    pub names_count_addr: *mut u32,
}

impl Arg for ARG_task_dyld_process_info_notify_get_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            names_addr: args[0] as mach_port_name_array_t,
            names_count_addr: args[1] as *mut u32,
        }
    }
}

impl Debug for ARG_task_dyld_process_info_notify_get_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "names_addr={:?}, names_count_addr={:?}",
            self.names_addr, self.names_count_addr
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_vm_protect_trap {
    pub target: mach2::port::mach_port_name_t,
    pub address: Uintptr,
    pub size: mach2::vm_types::mach_vm_size_t,
    pub set_maximum: i32,
    pub new_protection: mach2::vm_prot::vm_prot_t,
}

impl Arg for ARG__kernelrpc_mach_vm_protect_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            address: Uintptr::from(args[1]),
            size: args[2] as mach2::vm_types::mach_vm_size_t,
            set_maximum: args[3] as i32,
            new_protection: args[4] as mach2::vm_prot::vm_prot_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_vm_protect_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, address={:?}, size={:?}, set_maximum={:?}, new_protection={:?}",
            self.target, self.address, self.size, self.set_maximum, self.new_protection
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_vm_map_trap {
    pub target: mach2::port::mach_port_name_t,
    pub address: *mut mach2::vm_types::mach_vm_offset_t,
    pub size: mach2::vm_types::mach_vm_size_t,
    pub mask: mach2::vm_types::mach_vm_offset_t,
    pub flags: i32,
    pub cur_protection: mach2::vm_prot::vm_prot_t,
}

impl Arg for ARG__kernelrpc_mach_vm_map_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            address: args[1] as *mut mach2::vm_types::mach_vm_offset_t,
            size: args[2] as mach2::vm_types::mach_vm_size_t,
            mask: args[3] as mach2::vm_types::mach_vm_offset_t,
            flags: args[4] as i32,
            cur_protection: args[5] as mach2::vm_prot::vm_prot_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_vm_map_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, address={:?}, size={:?}, mask={:?}, flags={:?}, cur_protection={:?}",
            self.target, self.address, self.size, self.mask, self.flags, self.cur_protection
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_allocate_trap {
    pub target: mach2::port::mach_port_name_t,
    pub right: mach2::port::mach_port_right_t,
    pub name: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_allocate_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            right: args[1] as mach2::port::mach_port_right_t,
            name: args[2] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_allocate_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, right={:?}, name={:?}",
            self.target, self.right, self.name
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_deallocate_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_deallocate_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_deallocate_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "target={:?}, name={:?}", self.target, self.name)
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_mod_refs_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub right: mach2::port::mach_port_right_t,
    pub delta: mach2::port::mach_port_delta_t,
}

impl Arg for ARG__kernelrpc_mach_port_mod_refs_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            right: args[2] as mach2::port::mach_port_right_t,
            delta: args[3] as mach2::port::mach_port_delta_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_mod_refs_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, right={:?}, delta={:?}",
            self.target, self.name, self.right, self.delta
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_move_member_trap {
    pub target: mach2::port::mach_port_name_t,
    pub member: mach2::port::mach_port_name_t,
    pub after: mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_move_member_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            member: args[1] as mach2::port::mach_port_name_t,
            after: args[2] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_move_member_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, member={:?}, after={:?}",
            self.target, self.member, self.after
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_insert_right_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub poly: mach2::port::mach_port_name_t,
    pub polyPoly: mach2::message::mach_msg_type_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_insert_right_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            poly: args[2] as mach2::port::mach_port_name_t,
            polyPoly: args[3] as mach2::message::mach_msg_type_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_insert_right_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, poly={:?}, polyPoly={:?}",
            self.target, self.name, self.poly, self.polyPoly
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_insert_member_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub pset: mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_insert_member_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            pset: args[2] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_insert_member_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, pset={:?}",
            self.target, self.name, self.pset
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_extract_member_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub pset: mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_extract_member_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            pset: args[2] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_extract_member_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, pset={:?}",
            self.target, self.name, self.pset
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_construct_trap {
    pub target: mach2::port::mach_port_name_t,
    pub options: *mut mach2::port::mach_port_options_t,
    pub context: u64,
    pub name: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_construct_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            options: args[1] as *mut mach2::port::mach_port_options_t,
            context: args[2],
            name: args[3] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_construct_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, options={:?}, context={:?}, name={:?}",
            self.target, self.options, self.context, self.name
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_destruct_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub srdelta: mach2::port::mach_port_delta_t,
    pub guard: u64,
}

impl Arg for ARG__kernelrpc_mach_port_destruct_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            srdelta: args[2] as mach2::port::mach_port_delta_t,
            guard: args[3],
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_destruct_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, srdelta={:?}, guard={:?}",
            self.target, self.name, self.srdelta, self.guard
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_mach_msg_trap {
    pub msg: *mut mach2::message::mach_msg_header_t,
    pub option: mach2::message::mach_msg_option_t,
    pub send_size: mach2::message::mach_msg_size_t,
    pub rcv_size: mach2::message::mach_msg_size_t,
    pub rcv_name: mach2::port::mach_port_name_t,
    pub timeout: mach2::message::mach_msg_timeout_t,
    pub notify: mach2::port::mach_port_name_t,
}

impl Arg for ARG_mach_msg_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            msg: args[0] as *mut mach2::message::mach_msg_header_t,
            option: args[1] as mach2::message::mach_msg_option_t,
            send_size: args[2] as mach2::message::mach_msg_size_t,
            rcv_size: args[3] as mach2::message::mach_msg_size_t,
            rcv_name: args[4] as mach2::port::mach_port_name_t,
            timeout: args[5] as mach2::message::mach_msg_timeout_t,
            notify: args[6] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_mach_msg_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "msg={:?}, option={:?}, send_size={:?}, rcv_size={:?}, rcv_name={:?}, timeout={:?}, \
             notify={:?}",
            self.msg,
            self.option,
            self.send_size,
            self.rcv_size,
            self.rcv_name,
            self.timeout,
            self.notify
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_mach_msg_overwrite_trap {
    pub msg: *mut mach2::message::mach_msg_header_t,
    pub option: mach2::message::mach_msg_option_t,
    pub send_size: mach2::message::mach_msg_size_t,
    pub rcv_size: mach2::message::mach_msg_size_t,
    pub rcv_name: mach2::port::mach_port_name_t,
    pub timeout: mach2::message::mach_msg_timeout_t,
    pub priority: mach_msg_priority_t,
    pub rcv_msg: *mut mach2::message::mach_msg_header_t,
    pub rcv_limit: mach2::message::mach_msg_size_t,
}

impl Arg for ARG_mach_msg_overwrite_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            msg: args[0] as *mut mach2::message::mach_msg_header_t,
            option: args[1] as mach2::message::mach_msg_option_t,
            send_size: args[2] as mach2::message::mach_msg_size_t,
            rcv_size: args[3] as mach2::message::mach_msg_size_t,
            rcv_name: args[4] as mach2::port::mach_port_name_t,
            timeout: args[5] as mach2::message::mach_msg_timeout_t,
            priority: args[6] as mach_msg_priority_t,
            rcv_msg: args[7] as *mut mach2::message::mach_msg_header_t,
            rcv_limit: args[8] as mach2::message::mach_msg_size_t,
        }
    }
}

impl Debug for ARG_mach_msg_overwrite_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "msg={:?}, option={:?}, send_size={:?}, rcv_size={:?}, rcv_name={:?}, timeout={:?}, \
             priority={:?}, rcv_msg={:?}, rcv_limit={:?}",
            self.msg,
            self.option,
            self.send_size,
            self.rcv_size,
            self.rcv_name,
            self.timeout,
            self.priority,
            self.rcv_msg,
            self.rcv_limit
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_signal_trap {
    pub signal_name: mach2::port::mach_port_name_t,
}

impl Arg for ARG_semaphore_signal_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            signal_name: args[0] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_semaphore_signal_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "signal_name={:?}", self.signal_name)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_signal_all_trap {
    pub signal_name: mach2::port::mach_port_name_t,
}

impl Arg for ARG_semaphore_signal_all_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            signal_name: args[0] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_semaphore_signal_all_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "signal_name={:?}", self.signal_name)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_signal_thread_trap {
    pub signal_name: mach2::port::mach_port_name_t,
    pub thread_name: mach2::port::mach_port_name_t,
}

impl Arg for ARG_semaphore_signal_thread_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            signal_name: args[0] as mach2::port::mach_port_name_t,
            thread_name: args[1] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_semaphore_signal_thread_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "signal_name={:?}, thread_name={:?}",
            self.signal_name, self.thread_name
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_wait_trap {
    pub wait_name: mach2::port::mach_port_name_t,
}

impl Arg for ARG_semaphore_wait_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            wait_name: args[0] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_semaphore_wait_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "wait_name={:?}", self.wait_name)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_wait_signal_trap {
    pub wait_name: mach2::port::mach_port_name_t,
    pub signal_name: mach2::port::mach_port_name_t,
}

impl Arg for ARG_semaphore_wait_signal_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            wait_name: args[0] as mach2::port::mach_port_name_t,
            signal_name: args[1] as mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_semaphore_wait_signal_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "wait_name={:?}, signal_name={:?}",
            self.wait_name, self.signal_name
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_timedwait_trap {
    pub wait_name: mach2::port::mach_port_name_t,
    pub sec: u32,
    pub nsec: mach2::clock_types::clock_res_t,
}

impl Arg for ARG_semaphore_timedwait_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            wait_name: args[0] as mach2::port::mach_port_name_t,
            sec: args[1] as u32,
            nsec: args[2] as mach2::clock_types::clock_res_t,
        }
    }
}

impl Debug for ARG_semaphore_timedwait_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "wait_name={:?}, sec={:?}, nsec={:?}",
            self.wait_name, self.sec, self.nsec
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_semaphore_timedwait_signal_trap {
    pub wait_name: mach2::port::mach_port_name_t,
    pub signal_name: mach2::port::mach_port_name_t,
    pub sec: u32,
    pub nsec: mach2::clock_types::clock_res_t,
}

impl Arg for ARG_semaphore_timedwait_signal_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            wait_name: args[0] as mach2::port::mach_port_name_t,
            signal_name: args[1] as mach2::port::mach_port_name_t,
            sec: args[2] as u32,
            nsec: args[3] as mach2::clock_types::clock_res_t,
        }
    }
}

impl Debug for ARG_semaphore_timedwait_signal_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "wait_name={:?}, signal_name={:?}, sec={:?}, nsec={:?}",
            self.wait_name, self.signal_name, self.sec, self.nsec
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_get_attributes_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub flavor: mach_port_flavor_t,
    pub port_info_out: mach_port_info_t,
    pub port_info_outCnt: *mut mach2::message::mach_msg_type_number_t,
}

impl Arg for ARG__kernelrpc_mach_port_get_attributes_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            flavor: args[2] as mach_port_flavor_t,
            port_info_out: args[3] as mach_port_info_t,
            port_info_outCnt: args[4] as *mut mach2::message::mach_msg_type_number_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_get_attributes_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, flavor={:?}, port_info_out={:?}, port_info_outCnt={:?}",
            self.target, self.name, self.flavor, self.port_info_out, self.port_info_outCnt
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_guard_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub guard: u64,
    pub strict: i32,
}

impl Arg for ARG__kernelrpc_mach_port_guard_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            guard: args[2],
            strict: args[3] as i32,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_guard_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, guard={:?}, strict={:?}",
            self.target, self.name, self.guard, self.strict
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_unguard_trap {
    pub target: mach2::port::mach_port_name_t,
    pub name: mach2::port::mach_port_name_t,
    pub guard: u64,
}

impl Arg for ARG__kernelrpc_mach_port_unguard_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            name: args[1] as mach2::port::mach_port_name_t,
            guard: args[2],
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_unguard_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, name={:?}, guard={:?}",
            self.target, self.name, self.guard
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_mach_generate_activity_id {
    pub target: mach2::port::mach_port_name_t,
    pub count: i32,
    pub activity_id: *mut u64,
}

impl Arg for ARG_mach_generate_activity_id {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target: args[0] as mach2::port::mach_port_name_t,
            count: args[1] as i32,
            activity_id: args[2] as *mut u64,
        }
    }
}

impl Debug for ARG_mach_generate_activity_id {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target={:?}, count={:?}, activity_id={:?}",
            self.target, self.count, self.activity_id
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_task_name_for_pid {
    pub target_tport: mach2::port::mach_port_name_t,
    pub pid: i32,
    pub tn: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG_task_name_for_pid {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target_tport: args[0] as mach2::port::mach_port_name_t,
            pid: args[1] as i32,
            tn: args[2] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_task_name_for_pid {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target_tport={:?}, pid={:?}, tn={:?}",
            self.target_tport, self.pid, self.tn
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_task_for_pid {
    pub target_tport: mach2::port::mach_port_name_t,
    pub pid: i32,
    pub t: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG_task_for_pid {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target_tport: args[0] as mach2::port::mach_port_name_t,
            pid: args[1] as i32,
            t: args[2] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_task_for_pid {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target_tport={:?}, pid={:?}, t={:?}",
            self.target_tport, self.pid, self.t
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_pid_for_task {
    pub t: mach2::port::mach_port_name_t,
    pub x: *mut i32,
}

impl Arg for ARG_pid_for_task {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            t: args[0] as mach2::port::mach_port_name_t,
            x: args[1] as *mut i32,
        }
    }
}

impl Debug for ARG_pid_for_task {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "t={:?}, x={:?}", self.t, self.x)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_mach_msg2_trap {
    pub data: *mut libc::c_void,
    pub options: mach_msg_option64_t,
    pub msgh_bits_and_send_size: u64,
    pub msgh_remote_and_local_port: u64,
    pub msgh_voucher_and_id: u64,
    pub desc_count_and_rcv_name: u64,
    pub rcv_size_and_priority: u64,
    pub timeout: u64,
}

impl Arg for ARG_mach_msg2_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            data: args[0] as *mut libc::c_void,
            options: mach_msg_option64_t::from_bits(args[1]).expect("invalid options"),
            msgh_bits_and_send_size: args[2],
            msgh_remote_and_local_port: args[3],
            msgh_voucher_and_id: args[4],
            desc_count_and_rcv_name: args[5],
            rcv_size_and_priority: args[6],
            timeout: args[7],
        }
    }
}

impl Debug for ARG_mach_msg2_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "data={:?}, options={:?}, msgh_bits_and_send_size={:?}, \
             msgh_remote_and_local_port={:?}, msgh_voucher_and_id={:?}, \
             desc_count_and_rcv_name={:?}, rcv_size_and_priority={:?}, timeout={:?}",
            self.data,
            self.options,
            self.msgh_bits_and_send_size,
            self.msgh_remote_and_local_port,
            self.msgh_voucher_and_id,
            self.desc_count_and_rcv_name,
            self.rcv_size_and_priority,
            self.timeout
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_macx_swapon {
    pub filename: u64,
    pub flags: i32,
    pub size: i32,
    pub priority: i32,
}

impl Arg for ARG_macx_swapon {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            filename: args[0],
            flags: args[1] as i32,
            size: args[2] as i32,
            priority: args[3] as i32,
        }
    }
}

impl Debug for ARG_macx_swapon {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "filename={:?}, flags={:?}, size={:?}, priority={:?}",
            self.filename, self.flags, self.size, self.priority
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_macx_swapoff {
    pub filename: u64,
    pub flags: i32,
}

impl Arg for ARG_macx_swapoff {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            filename: args[0],
            flags: args[1] as i32,
        }
    }
}

impl Debug for ARG_macx_swapoff {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "filename={:?}, flags={:?}", self.filename, self.flags)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_macx_triggers {
    pub hi_water: i32,
    pub low_water: i32,
    pub flags: i32,
    pub alert_port: mach2::port::mach_port_t,
}

impl Arg for ARG_macx_triggers {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            hi_water: args[0] as i32,
            low_water: args[1] as i32,
            flags: args[2] as i32,
            alert_port: args[3] as mach2::port::mach_port_t,
        }
    }
}

impl Debug for ARG_macx_triggers {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "hi_water={:?}, low_water={:?}, flags={:?}, alert_port={:?}",
            self.hi_water, self.low_water, self.flags, self.alert_port
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_macx_backing_store_suspend {
    pub suspend: i32,
}

impl Arg for ARG_macx_backing_store_suspend {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            suspend: args[0] as i32,
        }
    }
}

impl Debug for ARG_macx_backing_store_suspend {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "suspend={:?}", self.suspend)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_macx_backing_store_recovery {
    pub pid: i32,
}

impl Arg for ARG_macx_backing_store_recovery {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            pid: args[0] as i32,
        }
    }
}

impl Debug for ARG_macx_backing_store_recovery {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "pid={:?}", self.pid)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_swtch_pri {
    pub pri: i32,
}

impl Arg for ARG_swtch_pri {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            pri: args[0] as i32,
        }
    }
}

impl Debug for ARG_swtch_pri {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(f, "pri={:?}", self.pri)
    }
}

#[derive(Clone, Copy)]
pub struct ARG_thread_switch {
    pub thread_name: mach2::port::mach_port_name_t,
    pub option: i32,
    pub option_time: mach2::message::mach_msg_timeout_t,
}

impl Arg for ARG_thread_switch {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            thread_name: args[0] as mach2::port::mach_port_name_t,
            option: args[1] as i32,
            option_time: args[2] as mach2::message::mach_msg_timeout_t,
        }
    }
}

impl Debug for ARG_thread_switch {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "thread_name={:?}, option={:?}, option_time={:?}",
            self.thread_name, self.option, self.option_time
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_clock_sleep_trap {
    pub clock_name: mach2::port::mach_port_name_t,
    pub sleep_type: mach2::clock_types::sleep_type_t,
    pub sleep_sec: i32,
    pub sleep_nsec: i32,
    pub wakeup_time: *mut mach2::clock_types::mach_timespec_t,
}

impl Arg for ARG_clock_sleep_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            clock_name: args[0] as mach2::port::mach_port_name_t,
            sleep_type: args[1] as mach2::clock_types::sleep_type_t,
            sleep_sec: args[2] as i32,
            sleep_nsec: args[3] as i32,
            wakeup_time: args[4] as *mut mach2::clock_types::mach_timespec_t,
        }
    }
}

impl Debug for ARG_clock_sleep_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "clock_name={:?}, sleep_type={:?}, sleep_sec={:?}, sleep_nsec={:?}, wakeup_time={:?}",
            self.clock_name, self.sleep_type, self.sleep_sec, self.sleep_nsec, self.wakeup_time
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_mach_vm_reclaim_update_kernel_accounting_trap {
    pub target_tport: mach2::port::mach_port_name_t,
    pub bytes_reclaimed: *mut u64,
}

impl Arg for ARG_mach_vm_reclaim_update_kernel_accounting_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target_tport: args[0] as mach2::port::mach_port_name_t,
            bytes_reclaimed: args[1] as *mut u64,
        }
    }
}

impl Debug for ARG_mach_vm_reclaim_update_kernel_accounting_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target_tport={:?}, bytes_reclaimed={:?}",
            self.target_tport, self.bytes_reclaimed
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_host_create_mach_voucher_trap {
    pub host: mach2::port::mach_port_name_t,
    pub recipes: mach2::mach_voucher_types::mach_voucher_attr_raw_recipe_array_t,
    pub recipes_size: i32,
    pub voucher: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG_host_create_mach_voucher_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            host: args[0] as mach2::port::mach_port_name_t,
            recipes: args[1] as mach2::mach_voucher_types::mach_voucher_attr_raw_recipe_array_t,
            recipes_size: args[2] as i32,
            voucher: args[3] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_host_create_mach_voucher_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "host={:?}, recipes={:?}, recipes_size={:?}, voucher={:?}",
            self.host, self.recipes, self.recipes_size, self.voucher
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_mach_voucher_extract_attr_recipe_trap {
    pub voucher_name: mach2::port::mach_port_name_t,
    pub key: mach2::mach_voucher_types::mach_voucher_attr_key_t,
    pub recipe: mach2::mach_voucher_types::mach_voucher_attr_raw_recipe_t,
    pub recipe_size: *mut mach2::message::mach_msg_type_number_t,
}

impl Arg for ARG_mach_voucher_extract_attr_recipe_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            voucher_name: args[0] as mach2::port::mach_port_name_t,
            key: args[1] as mach2::mach_voucher_types::mach_voucher_attr_key_t,
            recipe: args[2] as mach2::mach_voucher_types::mach_voucher_attr_raw_recipe_t,
            recipe_size: args[3] as *mut mach2::message::mach_msg_type_number_t,
        }
    }
}

impl Debug for ARG_mach_voucher_extract_attr_recipe_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "voucher_name={:?}, key={:?}, recipe={:?}, recipe_size={:?}",
            self.voucher_name, self.key, self.recipe, self.recipe_size
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_type_trap {
    pub task: mach2::mach_types::ipc_space_t,
    pub name: mach2::port::mach_port_name_t,
    pub ptype: *mut mach2::port::mach_port_type_t,
}

impl Arg for ARG__kernelrpc_mach_port_type_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            task: args[0] as mach2::mach_types::ipc_space_t,
            name: args[1] as mach2::port::mach_port_name_t,
            ptype: args[2] as *mut mach2::port::mach_port_type_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_type_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "task={:?}, name={:?}, ptype={:?}",
            self.task, self.name, self.ptype
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG__kernelrpc_mach_port_request_notification_trap {
    pub task: mach2::mach_types::ipc_space_t,
    pub name: mach2::port::mach_port_name_t,
    pub msgid: mach2::message::mach_msg_id_t,
    pub sync: mach2::port::mach_port_mscount_t,
    pub notify: mach2::port::mach_port_name_t,
    pub notifyPoly: mach2::message::mach_msg_type_name_t,
    pub previous: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG__kernelrpc_mach_port_request_notification_trap {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            task: args[0] as mach2::mach_types::ipc_space_t,
            name: args[1] as mach2::port::mach_port_name_t,
            msgid: args[2] as mach2::message::mach_msg_id_t,
            sync: args[3] as mach2::port::mach_port_mscount_t,
            notify: args[4] as mach2::port::mach_port_name_t,
            notifyPoly: args[5] as mach2::message::mach_msg_type_name_t,
            previous: args[6] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG__kernelrpc_mach_port_request_notification_trap {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "task={:?}, name={:?}, msgid={:?}, sync={:?}, notify={:?}, notifyPoly={:?}, \
             previous={:?}",
            self.task,
            self.name,
            self.msgid,
            self.sync,
            self.notify,
            self.notifyPoly,
            self.previous
        )
    }
}

#[derive(Clone, Copy)]
pub struct ARG_debug_control_port_for_pid {
    pub target_tport: mach2::port::mach_port_name_t,
    pub pid: i32,
    pub t: *mut mach2::port::mach_port_name_t,
}

impl Arg for ARG_debug_control_port_for_pid {
    #[inline]
    fn decode(args: &[u64; 9]) -> Self {
        Self {
            target_tport: args[0] as mach2::port::mach_port_name_t,
            pid: args[1] as i32,
            t: args[2] as *mut mach2::port::mach_port_name_t,
        }
    }
}

impl Debug for ARG_debug_control_port_for_pid {
    #[inline]
    fn fmt(&self, f: &mut Formatter<'_>) -> FmtResult {
        write!(
            f,
            "target_tport={:?}, pid={:?}, t={:?}",
            self.target_tport, self.pid, self.t
        )
    }
}

#[repr(u64)]
#[derive(Debug, Clone, Copy)]
pub enum MachTrap {
    _kernelrpc_mach_vm_allocate_trap(ARG__kernelrpc_mach_vm_allocate_trap) = 10,
    _kernelrpc_mach_vm_purgable_control_trap(ARG__kernelrpc_mach_vm_purgable_control_trap) = 11,
    _kernelrpc_mach_vm_deallocate_trap(ARG__kernelrpc_mach_vm_deallocate_trap) = 12,
    task_dyld_process_info_notify_get_trap(ARG_task_dyld_process_info_notify_get_trap) = 13,
    _kernelrpc_mach_vm_protect_trap(ARG__kernelrpc_mach_vm_protect_trap) = 14,
    _kernelrpc_mach_vm_map_trap(ARG__kernelrpc_mach_vm_map_trap) = 15,
    _kernelrpc_mach_port_allocate_trap(ARG__kernelrpc_mach_port_allocate_trap) = 16,
    _kernelrpc_mach_port_deallocate_trap(ARG__kernelrpc_mach_port_deallocate_trap) = 18,
    _kernelrpc_mach_port_mod_refs_trap(ARG__kernelrpc_mach_port_mod_refs_trap) = 19,
    _kernelrpc_mach_port_move_member_trap(ARG__kernelrpc_mach_port_move_member_trap) = 20,
    _kernelrpc_mach_port_insert_right_trap(ARG__kernelrpc_mach_port_insert_right_trap) = 21,
    _kernelrpc_mach_port_insert_member_trap(ARG__kernelrpc_mach_port_insert_member_trap) = 22,
    _kernelrpc_mach_port_extract_member_trap(ARG__kernelrpc_mach_port_extract_member_trap) = 23,
    _kernelrpc_mach_port_construct_trap(ARG__kernelrpc_mach_port_construct_trap) = 24,
    _kernelrpc_mach_port_destruct_trap(ARG__kernelrpc_mach_port_destruct_trap) = 25,
    mach_reply_port = 26,
    thread_self_trap = 27,
    task_self_trap = 28,
    host_self_trap = 29,
    mach_msg_trap(ARG_mach_msg_trap) = 31,
    mach_msg_overwrite_trap(ARG_mach_msg_overwrite_trap) = 32,
    semaphore_signal_trap(ARG_semaphore_signal_trap) = 33,
    semaphore_signal_all_trap(ARG_semaphore_signal_all_trap) = 34,
    semaphore_signal_thread_trap(ARG_semaphore_signal_thread_trap) = 35,
    semaphore_wait_trap(ARG_semaphore_wait_trap) = 36,
    semaphore_wait_signal_trap(ARG_semaphore_wait_signal_trap) = 37,
    semaphore_timedwait_trap(ARG_semaphore_timedwait_trap) = 38,
    semaphore_timedwait_signal_trap(ARG_semaphore_timedwait_signal_trap) = 39,
    _kernelrpc_mach_port_get_attributes_trap(ARG__kernelrpc_mach_port_get_attributes_trap) = 40,
    _kernelrpc_mach_port_guard_trap(ARG__kernelrpc_mach_port_guard_trap) = 41,
    _kernelrpc_mach_port_unguard_trap(ARG__kernelrpc_mach_port_unguard_trap) = 42,
    mach_generate_activity_id(ARG_mach_generate_activity_id) = 43,
    task_name_for_pid(ARG_task_name_for_pid) = 44,
    task_for_pid(ARG_task_for_pid) = 45,
    pid_for_task(ARG_pid_for_task) = 46,
    mach_msg2_trap(ARG_mach_msg2_trap) = 47,
    macx_swapon(ARG_macx_swapon) = 48,
    macx_swapoff(ARG_macx_swapoff) = 49,
    thread_get_special_reply_port = 50,
    macx_triggers(ARG_macx_triggers) = 51,
    macx_backing_store_suspend(ARG_macx_backing_store_suspend) = 52,
    macx_backing_store_recovery(ARG_macx_backing_store_recovery) = 53,
    pfz_exit = 58,
    swtch_pri(ARG_swtch_pri) = 59,
    swtch = 60,
    thread_switch(ARG_thread_switch) = 61,
    clock_sleep_trap(ARG_clock_sleep_trap) = 62,
    mach_vm_reclaim_update_kernel_accounting_trap(
        ARG_mach_vm_reclaim_update_kernel_accounting_trap,
    ) = 63,
    host_create_mach_voucher_trap(ARG_host_create_mach_voucher_trap) = 70,
    mach_voucher_extract_attr_recipe_trap(ARG_mach_voucher_extract_attr_recipe_trap) = 72,
    _kernelrpc_mach_port_type_trap(ARG__kernelrpc_mach_port_type_trap) = 76,
    _kernelrpc_mach_port_request_notification_trap(
        ARG__kernelrpc_mach_port_request_notification_trap,
    ) = 77,
    _exclaves_ctl_trap = 88,
    mach_timebase_info_trap = 89,
    mach_wait_until_trap = 90,
    mk_timer_create_trap = 91,
    mk_timer_destroy_trap = 92,
    mk_timer_arm_trap = 93,
    mk_timer_cancel_trap = 94,
    mk_timer_arm_leeway_trap = 95,
    debug_control_port_for_pid(ARG_debug_control_port_for_pid) = 96,
    iokit_user_client_trap = 100,
    Unknown(u64),
}

impl MachTrap {
    pub fn decode(id: u64, args: &[u64; 9]) -> Self {
        match id {
            10 => Self::_kernelrpc_mach_vm_allocate_trap(Arg::decode(args)),
            11 => Self::_kernelrpc_mach_vm_purgable_control_trap(Arg::decode(args)),
            12 => Self::_kernelrpc_mach_vm_deallocate_trap(Arg::decode(args)),
            13 => Self::task_dyld_process_info_notify_get_trap(Arg::decode(args)),
            14 => Self::_kernelrpc_mach_vm_protect_trap(Arg::decode(args)),
            15 => Self::_kernelrpc_mach_vm_map_trap(Arg::decode(args)),
            16 => Self::_kernelrpc_mach_port_allocate_trap(Arg::decode(args)),
            18 => Self::_kernelrpc_mach_port_deallocate_trap(Arg::decode(args)),
            19 => Self::_kernelrpc_mach_port_mod_refs_trap(Arg::decode(args)),
            20 => Self::_kernelrpc_mach_port_move_member_trap(Arg::decode(args)),
            21 => Self::_kernelrpc_mach_port_insert_right_trap(Arg::decode(args)),
            22 => Self::_kernelrpc_mach_port_insert_member_trap(Arg::decode(args)),
            23 => Self::_kernelrpc_mach_port_extract_member_trap(Arg::decode(args)),
            24 => Self::_kernelrpc_mach_port_construct_trap(Arg::decode(args)),
            25 => Self::_kernelrpc_mach_port_destruct_trap(Arg::decode(args)),
            26 => Self::mach_reply_port,
            27 => Self::thread_self_trap,
            28 => Self::task_self_trap,
            29 => Self::host_self_trap,
            31 => Self::mach_msg_trap(Arg::decode(args)),
            32 => Self::mach_msg_overwrite_trap(Arg::decode(args)),
            33 => Self::semaphore_signal_trap(Arg::decode(args)),
            34 => Self::semaphore_signal_all_trap(Arg::decode(args)),
            35 => Self::semaphore_signal_thread_trap(Arg::decode(args)),
            36 => Self::semaphore_wait_trap(Arg::decode(args)),
            37 => Self::semaphore_wait_signal_trap(Arg::decode(args)),
            38 => Self::semaphore_timedwait_trap(Arg::decode(args)),
            39 => Self::semaphore_timedwait_signal_trap(Arg::decode(args)),
            40 => Self::_kernelrpc_mach_port_get_attributes_trap(Arg::decode(args)),
            41 => Self::_kernelrpc_mach_port_guard_trap(Arg::decode(args)),
            42 => Self::_kernelrpc_mach_port_unguard_trap(Arg::decode(args)),
            43 => Self::mach_generate_activity_id(Arg::decode(args)),
            44 => Self::task_name_for_pid(Arg::decode(args)),
            45 => Self::task_for_pid(Arg::decode(args)),
            46 => Self::pid_for_task(Arg::decode(args)),
            47 => Self::mach_msg2_trap(Arg::decode(args)),
            48 => Self::macx_swapon(Arg::decode(args)),
            49 => Self::macx_swapoff(Arg::decode(args)),
            50 => Self::thread_get_special_reply_port,
            51 => Self::macx_triggers(Arg::decode(args)),
            52 => Self::macx_backing_store_suspend(Arg::decode(args)),
            53 => Self::macx_backing_store_recovery(Arg::decode(args)),
            58 => Self::pfz_exit,
            59 => Self::swtch_pri(Arg::decode(args)),
            60 => Self::swtch,
            61 => Self::thread_switch(Arg::decode(args)),
            62 => Self::clock_sleep_trap(Arg::decode(args)),
            63 => Self::mach_vm_reclaim_update_kernel_accounting_trap(Arg::decode(args)),
            70 => Self::host_create_mach_voucher_trap(Arg::decode(args)),
            72 => Self::mach_voucher_extract_attr_recipe_trap(Arg::decode(args)),
            76 => Self::_kernelrpc_mach_port_type_trap(Arg::decode(args)),
            77 => Self::_kernelrpc_mach_port_request_notification_trap(Arg::decode(args)),
            88 => Self::_exclaves_ctl_trap,
            89 => Self::mach_timebase_info_trap,
            90 => Self::mach_wait_until_trap,
            91 => Self::mk_timer_create_trap,
            92 => Self::mk_timer_destroy_trap,
            93 => Self::mk_timer_arm_trap,
            94 => Self::mk_timer_cancel_trap,
            95 => Self::mk_timer_arm_leeway_trap,
            96 => Self::debug_control_port_for_pid(Arg::decode(args)),
            100 => Self::iokit_user_client_trap,
            _ => Self::Unknown(id),
        }
    }
}
