//! Generated by `genmachtraps.py`, DO NOT EDIT.

use crate::aarch64::{
    syscall::{mach::MachTrap, Syscall},
    virtos::syscall::mach,
};

impl Syscall<'_> {
    pub(super) fn dispatch_mach(&mut self, mach: MachTrap) {
        macro_rules! handle_mach_trap {
            ($($name:ident $(($($args:tt)*))?),+ $(,)?) => {
                match mach {
                    $(
                        handle_mach_trap!(@CASE $name [$(($($args)*))?]) => {
                            handle_mach_trap!(@IMPL $name [$(($($args)*))?]);
                        }
                    )*
                    MachTrap::Unknown(..) => {
                        self.args[0] = mach2::kern_return::KERN_INVALID_ARGUMENT as u64;
                    }
                }
            };
            (@CASE $name:ident [($args:ident)]) => { MachTrap::$name($args) };
            (@CASE $name:ident [(..)]) => { MachTrap::$name(..) };
            (@CASE $name:ident [()]) => { MachTrap::$name };
            (@CASE $name:ident []) => { MachTrap::$name };
            (@IMPL $name:ident [($args:ident)]) => { self.args[0] = mach::$name(self.cpu, $args) as u64; };
            (@IMPL $name:ident [(..)]) => { self.forward() };
            (@IMPL $name:ident [()]) => { self.args[0] = mach::$name(self.cpu) as u64; };
            (@IMPL $name:ident []) => { self.forward() };
        }
        handle_mach_trap! {
            _kernelrpc_mach_vm_allocate_trap(args),
            _kernelrpc_mach_vm_purgable_control_trap(args),
            _kernelrpc_mach_vm_deallocate_trap(args),
            task_dyld_process_info_notify_get_trap(args),
            _kernelrpc_mach_vm_protect_trap(args),
            _kernelrpc_mach_vm_map_trap(args),
            _kernelrpc_mach_port_allocate_trap(args),
            _kernelrpc_mach_port_deallocate_trap(..),
            _kernelrpc_mach_port_mod_refs_trap(..),
            _kernelrpc_mach_port_move_member_trap(..),
            _kernelrpc_mach_port_insert_right_trap(..),
            _kernelrpc_mach_port_insert_member_trap(..),
            _kernelrpc_mach_port_extract_member_trap(..),
            _kernelrpc_mach_port_construct_trap(args),
            _kernelrpc_mach_port_destruct_trap(..),
            mach_reply_port,
            thread_self_trap,
            task_self_trap,
            host_self_trap,
            mach_msg_trap(args),
            mach_msg_overwrite_trap(args),
            semaphore_signal_trap(..),
            semaphore_signal_all_trap(..),
            semaphore_signal_thread_trap(..),
            semaphore_wait_trap(..),
            semaphore_wait_signal_trap(..),
            semaphore_timedwait_trap(..),
            semaphore_timedwait_signal_trap(..),
            _kernelrpc_mach_port_get_attributes_trap(args),
            _kernelrpc_mach_port_guard_trap(..),
            _kernelrpc_mach_port_unguard_trap(..),
            mach_generate_activity_id(args),
            task_name_for_pid(args),
            task_for_pid(args),
            pid_for_task(args),
            mach_msg2_trap(args),
            macx_swapon(..),
            macx_swapoff(..),
            thread_get_special_reply_port,
            macx_triggers(..),
            macx_backing_store_suspend(..),
            macx_backing_store_recovery(..),
            pfz_exit,
            swtch_pri(..),
            swtch,
            thread_switch(..),
            clock_sleep_trap(args),
            mach_vm_reclaim_update_kernel_accounting_trap(args),
            host_create_mach_voucher_trap(args),
            mach_voucher_extract_attr_recipe_trap(args),
            _kernelrpc_mach_port_type_trap(args),
            _kernelrpc_mach_port_request_notification_trap(args),
            _exclaves_ctl_trap,
            mach_timebase_info_trap,
            mach_wait_until_trap,
            mk_timer_create_trap,
            mk_timer_destroy_trap,
            mk_timer_arm_trap,
            mk_timer_cancel_trap,
            mk_timer_arm_leeway_trap,
            debug_control_port_for_pid(args),
            iokit_user_client_trap,
        }
    }
}
